""":class:`.BaseCircuitBackend` definition.
"""

from __future__ import annotations

from abc import abstractmethod
from collections.abc import Sequence, Mapping
import textwrap
from typing import ClassVar, Type, TypeAlias, TypeVar

from loqs.internal import SeqCastable, Displayable


# Generic type variable to stand-in for derived class below
T = TypeVar("T", bound="BasePhysicalCircuit")


class BasePhysicalCircuit(SeqCastable, Displayable):
    """Base class for an object that can holds a physical quantum circuit."""

    # Class attributes
    name: ClassVar[str]
    """Name of circuit backend"""

    CACHE_ON_SERIALIZE: ClassVar[bool] = True

    ## Dunder methods
    @abstractmethod
    def __init__(
        self,
        circuit: object,
        qubit_labels: Sequence | None = None,
    ) -> None:
        """
        Parameters
        ----------
        circuit:
            The underlying circuit object

        qubit_labels:
            Qubit labels to use for the circuit
        """
        if qubit_labels is not None:
            self.set_qubit_labels_inplace(qubit_labels)

    def __str__(self) -> str:
        s = f"Physical {self.name} circuit:\n"
        s += textwrap.indent(str(self.circuit), "  ")
        return s

    def __repr__(self) -> str:
        return f"Physical {self.name} circuit: {repr(self.circuit)}"

    def __hash__(self) -> int:
        return hash(repr(self))

    # Class methods
    @classmethod
    def from_circuit_tiling(
        cls: Type[T],
        template_circuit: BasePhysicalCircuit,
        qubit_labels: Sequence,
        tile_qubits: Sequence[Sequence | Mapping],
        merge_offsets: int | Sequence[int] = 0,
    ) -> T:
        """Create a tiled circuit from a template and list of qubits.

        Parameters
        ----------
        template_circuit:
            The template circuit to use while tiling. Note that this is not
            itself included as a tile, so qubit labels do not have to match
            any labels in the final circuit.

        qubit_labels:
            The complete qubit labels for the tiled circuit.

        tile_qubits:
            A list of qubit label mappings for the tiles, which can either
            be given as a dict of old -> new labels, or simply as a list of labels
            (in which case the mapping will be generated by zipping with
            :attr:`.qubit_labels`). Tiles will be added in the provided order
            of the mappings.
            If a new qubit label is given as None, then any operations acting on that
            qubit in circuit will be dropped. This can be useful when it is important
            to keep circuit scheduling at the edges of patches, e.g. weight-2 and weight-4
            stabilizer checks in the surface code have the same schedule pattern to
            allow for full parallelization between the stabilizers.

        merge_offsets:
            A list of offsets to use when merging tiles. If a single value is
            given, it is applied to all tiles. This defaults to 0, which stacks
            all circuits vertically (i.e. they all start at the same time). A value of
            :attr:``.depth`` would result in each tile being appended,
            i.e. with no overlap. Negative values are computed from ``circuit.depth``,
            i.e. an offset of -1 is equivalent to ``circuit.depth-1``.

        Returns
        -------
        tiled_circuit:
            The resulting tiled circuit
        """
        # Initialize empty circuit with full labels
        tiled_circuit = cls([], qubit_labels)

        # Cast the template to same type as this class for interoperability
        circuit = cls.cast(template_circuit)

        if isinstance(merge_offsets, int):
            merge_offsets = [merge_offsets] * len(tile_qubits)

        # Add each tile
        for i, (tiling, offset) in enumerate(zip(tile_qubits, merge_offsets)):
            if isinstance(tiling, Mapping):
                qubit_mapping = tiling
            else:
                qubit_mapping = {
                    old_q: new_q
                    for old_q, new_q in zip(circuit.qubit_labels, tiling)
                }

            # Check for any dropped qubits (i.e. specified as None)
            dropped_qubits = []
            kept_mapping = {}
            for k, v in qubit_mapping.items():
                if v is None:
                    dropped_qubits.append(k)
                else:
                    kept_mapping[k] = v

            # Map qubits (dropping ops if needed)
            new_tiling = circuit.delete_qubits(dropped_qubits)
            new_tiling.map_qubit_labels_inplace(kept_mapping)

            # Compute true offset
            if offset < 0:
                # Compute from end of tiling, independent of how many we've already done
                offset = tiled_circuit.depth - offset
            else:
                # Offset needs to account for how many circuits we've already added
                offset *= i

            tiled_circuit.merge_inplace(new_tiling, offset)

        return tiled_circuit

    # Instance properties
    @property
    @abstractmethod
    def circuit(self) -> object:
        """Getter for underlying circuit object"""
        pass

    @property
    @abstractmethod
    def depth(self) -> int:
        """The length/depth of the circuit (number of layers)."""
        pass

    @property
    @abstractmethod
    def qubit_labels(self) -> Sequence:
        """Get the qubit labels of an underlying circuit.

        Returns
        -------
        list
            Qubit labels
        """
        pass

    # Instance methods
    def append(self: T, circuit: BasePhysicalCircuit) -> T:
        """Append another circuit to a copy of this circuit.

        Parameters
        ----------
        circuit:
            See :meth:`.append_inplace`

        Returns
        -------
        BasePhysicalCircuit
            A modified copy of the circuit.
        """
        modified_circuit = self.copy()
        modified_circuit.append_inplace(circuit)
        return modified_circuit

    def append_inplace(self, circuit: BasePhysicalCircuit) -> None:
        """Append another circuit in-place to this circuit.

        Parameters
        ----------
        circuit:
            Circuit to append
        """
        self.insert_inplace(circuit, self.depth)

    @abstractmethod
    def copy(self: T) -> T:
        """Copy a circuit object.

        Returns
        -------
        BasePhysicalCircuit
            Copied circuit
        """
        pass

    def delete_qubits(self: T, qubits_to_delete: Sequence) -> T:
        """Delete qubit lines in a copy of the provided circuit.

        Operations involving the deleted qubits are also removed.

        Parameters
        ----------
        qubit_to_delete:
            See :meth:`.delete_qubits_inplace`

        Returns
        -------
        BasePhysicalCircuit
            A modified copy of the circuit.
        """
        modified_circuit = self.copy()
        modified_circuit.delete_qubits_inplace(qubits_to_delete)
        return modified_circuit

    @abstractmethod
    def delete_qubits_inplace(self, qubits_to_delete: Sequence) -> None:
        """Delete qubit lines in-place in a provided circuit.

        Parameters
        ----------
        qubits_to_delete:
            List of qubit lines to remove.
        """
        pass

    @abstractmethod
    def get_possible_discrete_error_locations(self) -> list[tuple[int, int]]:
        """Return all possible circuit locations where errors can be injected.

        Returns
        -------
        list
            List of 2-tuples of (layer index, qubit index) describing all
            possible circuit locations where a single-qubit error can be injected.
        """
        pass

    def insert(self: T, circuit: BasePhysicalCircuit, idx: int) -> T:
        """Insert another circuit to a copy of this circuit.

        Parameters
        ----------
        circuit:
            See :meth:`.insert_inplace`

        idx:
            See :meth:`.insert_inplace`

        Returns
        -------
        BasePhysicalCircuit
            A modified copy of the circuit.
        """
        modified_circuit = self.copy()
        modified_circuit.insert_inplace(circuit, idx)
        return modified_circuit

    @abstractmethod
    def insert_inplace(self, circuit: BasePhysicalCircuit, idx: int) -> None:
        """Insert another circuit to this circuit.

        Parameters
        ----------
        circuit:
            Circuit to insert

        idx:
            Starting index to begin insert. If -1, append to the end.
        """
        pass

    def map_qubit_labels(self: T, qubit_mapping: Mapping) -> T:
        """Substitute qubit labels in underlying circuit objects.

        Parameters
        ----------
        qubit_mapping:
            See :meth:`.map_qubit_labels_inplace`

        Returns
        -------
        BasePhysicalCircuit
            A copy of the circuit with mapped qubits.
        """
        # Providing a default implementation for circuits
        # that can be modified in-place
        modified_circuit = self.copy()
        modified_circuit.map_qubit_labels_inplace(qubit_mapping)
        return modified_circuit

    @abstractmethod
    def map_qubit_labels_inplace(self, qubit_mapping: Mapping) -> None:
        """Substitute qubit labels in underlying circuit objects.

        Parameters
        ----------
        qubit_mapping:
            Mapping from old qubit labels to new qubit labels.
            If a qubit label is not provided, it remains unchanged.
        """
        pass

    def merge(self: T, circuit: BasePhysicalCircuit, idx: int) -> T:
        """Merge another circuit to a copy of this circuit.

        While :meth:`.insert` adds new layers, :meth:`.merge`
        will try to add operations to existing layers.

        Parameters
        ----------
        Other Parameters:
            See :meth:`.merge_inplace`

        Returns
        -------
        modified_circuit:
            A modified copy of the circuit.
        """
        modified_circuit = self.copy()
        modified_circuit.merge_inplace(circuit, idx)
        return modified_circuit

    @abstractmethod
    def merge_inplace(self, circuit: BasePhysicalCircuit, idx: int) -> None:
        """Merge another circuit to this circuit.

        While :meth:`.insert_inplace` adds new layers,
        :meth:`.merge_inplace` will try to add operations to
        existing layers.

        Parameters
        ----------
        circuit:
            Circuit to merge

        idx:
            Layer index to start merge
        """
        pass

    def pad_single_qubit_idles(self: T, idle_name: str) -> T:
        """Replace empty spaces in layers with an idle operation.

        Parameters
        ----------
        Other Parameters:
            See :meth:`.pad_single_qubit_idles_inplace`

        Returns
        -------
        BasePhysicalCircuit
            A modified copy of the circuit.
        """
        modified_circuit = self.copy()
        modified_circuit.pad_single_qubit_idles_inplace(idle_name)
        return modified_circuit

    def pad_single_qubit_idles_inplace(self, idle_name: str) -> None:
        """Replace empty spaces in layers with an idle operation.

        Parameters
        ----------
        idle_name:
            Label name to use when inserting idles.
        """
        # Shortcut for pad by durations
        self.pad_single_qubit_idles_by_duration_inplace(
            {0: idle_name}, {}, default_duration=0
        )

    def pad_single_qubit_idles_by_duration(
        self: T,
        idle_names: Mapping[int | float, str],
        durations: Mapping[str, int | float],
        default_duration: int | float | None = None,
        empty_layer_idle: str | None = None,
    ) -> T:
        """Replace empty spaces in layers with duration-specific idles.

        Parameters
        ----------
        idle_names:
            See :meth:`.pad_single_qubit_idles_by_duration_inplace`

        durations:
            See :meth:`.pad_single_qubit_idles_by_duration_inplace`

        default_duration:
            See :meth:`.pad_single_qubit_idles_by_duration_inplace`

        empty_layer_idle:
            See :meth:`.pad_single_qubit_idles_by_duration_inplace`

        Returns
        -------
        BasePhysicalCircuit
            A modified copy of the circuit.
        """
        modified_circuit = self.copy()
        modified_circuit.pad_single_qubit_idles_by_duration_inplace(
            idle_names,
            durations,
            default_duration,
            empty_layer_idle,
        )
        return modified_circuit

    @abstractmethod
    def pad_single_qubit_idles_by_duration_inplace(
        self,
        idle_names: Mapping[int | float, str],
        durations: Mapping[str, int | float],
        default_duration: int | float | None = None,
        empty_layer_idle: str | None = None,
    ) -> None:
        """Replace empty spaces in layers with duration-specific idles.

        This computes the max duration of all other operations in
        the layer, and then inserts the appropriate idle.

        Parameters
        ----------
        idle_names:
            A mapping from layer duration to idle operation name.

        durations:
            A mapping from operation names to durations.

        default_duration:
            Default duration to use if not provided in `durations`.
            Defaults to None, which will cause a KeyError to be thrown.

        empty_layer_idle:
            Label to use for qubits in a completely empty label.
            Defaults to None, which inserts no idles.
        """
        pass

    def set_qubit_labels(self: T, qubit_labels: Sequence) -> T:
        """Set the qubit labels of an underlying circuit.

        Parameters
        ----------
        qubit_labels:
            See :meth:`.set_qubit_labels_inplace`

        Returns
        -------
        BasePhysicalCircuit
            A modified copy of the circuit.
        """
        # Providing a default implementation for circuits
        # that can be modified in-place
        modified_circuit = self.copy()
        modified_circuit.set_qubit_labels_inplace(qubit_labels)
        return modified_circuit

    @abstractmethod
    def set_qubit_labels_inplace(self, qubit_labels: Sequence) -> None:
        """Set the qubit labels of an underlying circuit.

        Note that depending on the backend, this may only adjust
        the qubit labels and not the operations in the circuit.
        For a complete change of qubit labels, see
        :meth:`map_qubit_labels_inplace` instead.

        Parameters
        ----------
        qubit_labels:
            Qubit labels to assign to circuit.
        """
        pass

    @classmethod
    def _from_serialization(
        cls: type[T], state: Mapping, serial_id_to_obj_cache=None
    ) -> T:
        qubit_labels = state["qubit_labels"]
        circuit = cls._deserialize_circuit(state["circuit"], qubit_labels)
        return cls(circuit, qubit_labels)

    def _to_serialization(self, hash_to_serial_id_cache=None) -> dict:
        state = super()._to_serialization()
        state.update(
            {
                "circuit": self._serialize_circuit(),
                "qubit_labels": self.qubit_labels,
            }
        )
        return state

    @classmethod
    @abstractmethod
    def _deserialize_circuit(
        cls,
        serial_circuit: str | list | dict,
        qubit_labels: Sequence | None = None,
    ) -> object:
        """Helper function to deserialize a circuit.

        Derived classes should implement this for
        deserialization to work.
        """
        pass

    @abstractmethod
    def _serialize_circuit(self) -> str | list | dict:
        """Helper function to serialize a circuit.

        Derived classes should implement this for
        serialization to work.
        """
        pass
