stages:
  - lint
  - test
  - docs

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

default:
  # https://pip.pypa.io/en/stable/topics/caching/
  cache:
    paths:
      - .cache/pip

Run code formatting and linting:
  stage: lint
  image: python:${PYTHON_VERSION}
  script:
    - pip install -e ".[dev]"
    - black --fast loqs
    - flake8 loqs

Run unit tests:
  stage: lint
  image: python:${PYTHON_VERSION}
  script:
    - python --version; pip --version # For debugging
    - pip install ".[pygsti,quantumsim,test]"
    - pytest loqs # This should run doctests in docstrings
    - pytest test # This should run unit tests

Build documentation:
  stage: docs
  script:
    - pip install ".[docs]"
    - jupyter-book build docs
    - mv docs/_build/html/ ../public/
  artifacts:
    paths:
      - public
    expire_in: never
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
