stages:
  - test
  - docs

include:
  - template: Security/SAST.gitlab-ci.yml

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - conda activate gitlab-runner-loqs
  - pip install ".[all]"

Run unit tests:
  stage: test
  image: quay.sandia.gov/dice/rhel8-minimal-python
  allow_failure: true
  script:
    - tox run

Build documentation:
  stage: docs
  image: quay.sandia.gov/dice/rhel8-minimal-python
  script:
    - jupyter-book build docs
    - mv docs/_build/html public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
