stages:
  - test
  - docs

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  CI_DEBUG_TRACE: "true"

cache:
  paths:
    - .cache/pip

Run unit tests:
  stage: test
  image: python:3.11
  allow_failure: true
  script:
    - conda activate gitlab-runner-loqs
    - pip install ".[test]"
    - tox run

Build documentation:
  stage: docs
  image: python:3.11
  script:
    - conda activate gitlab-runner-loqs
    - pip install ".[docs,pygsti,quantumsim]"
    - jupyter-book build docs
    - mv docs/_build/html public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
