site_name: LoQS Documentation

nav:
  - Home: index.md
  - Getting Started:
      - Install: getting-started/install.md
      - Overview: getting-started/overview.md
      - Workflow: getting-started/workflow.md
  # - Object Quickstart:
  #   - Histories:
  #     - object-quickstart/history.md
  #     - object-quickstart/frame.md
  #     - object-quickstart/recordables.md
  #   - Instructions:
  #     - object-quickstart/instructions.md
  #     - object-quickstart/stack.md
  #     - object-quickstart/builders.md
  #   - Codes:
  #     - object-quickstart/codes.md
  #     - object-quickstart/codepacks.md
  #   - object-quickstart/program.md
  #   - object-quickstart/backends.md
  # - Tutorials:
  #   - tutorials/buildinstruction.md
  #   - tutorials/buildqeccode.md
  #   - tutorials/daskparallelism.md
  # - Examples:
  #   - examples/runlogst.md
  #   - examples/fttests.md
  #   - examples/timedepmodel.md
  - Developer Zone:
      - Dev Guide: dev-zone/devguide.md
  - API Reference: /reference
  - Bibliography: references.md

theme:
  name: material
  logo: logo_icon.png
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - content.code.copy

markdown_extensions:
  - footnotes
  - toc:
      permalink: true
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight

plugins:
  - search
  - marimo:
      display_code: true
  - bibtex:
      bib_file: docs/references.bib
      csl_file: docs/american-physical-society-et-al.csl
  - mkdocs-simple-hooks:
      hooks:
        on_page_markdown: docs_scripts.main_hooks:on_page_markdown