[mypy]
ignore_missing_imports = True
exclude = (?x)(
    ^tests/tools/migrate_fixtures/
    |^tests/backends/fixtures/generate_reps_fixtures\.py$
    |^tests/backends/model/fixtures/generate_model_fixtures\.py$
  )
