[tox]
requires =
    tox>=4
env_list = clean,lint,type,py311,report

[testenv]
description = run unit tests (with backends)
deps =
    mock>=5
    numpy
    pytest>=8
    pytest-cov>=5
    pygsti>=0.9.12
    quantumsim==0.2.0
commands =
    pytest --cov --cov-append tests

[testenv:lint]
description = run linters
skip_install = true
deps =
    black>=24
    flake8>=7
commands =
    black {posargs:loqs}
    flake8 {posargs:loqs}

[testenv:type]
description = run type checks
deps =
    mypy>=1
commands =
    mypy {posargs:loqs}

[testenv:report]
description = generate a coverage report
deps = coverage
skip_install = true
commands =
    coverage report
    coverage html

[testenv:clean]
description = clean coverage between runs
deps = coverage
skip_install = true
commands = coverage erase
