"""Tester for loqs.core.quantumprogram"""

import os
from tempfile import NamedTemporaryFile
import pytest

from loqs.backends import GateRep, PyGSTiPhysicalCircuit, ListPhysicalCircuit, PyGSTiNoiseModel, DictNoiseModel, QSimQuantumState, STIMQuantumState
from loqs.core import QuantumProgram
from loqs.codepacks import codepack_5_1_3_quantinuum2022 as codepack_5_1_3

@pytest.mark.skipif(os.getenv("CI", "false") == "true", reason="Breaks GitHub runners?")
class TestQuantumProgram:

    # TODO: This is currently only an integrated test depending on a codepack
    # Make actual unit tests, and probably convert this to a codepack test
    
    # Note that tests will be labeled state-model-circuit with this stacking
    @pytest.mark.parametrize("circuit_backend", [PyGSTiPhysicalCircuit, ListPhysicalCircuit])
    @pytest.mark.parametrize("model_backend", [PyGSTiNoiseModel, DictNoiseModel])
    @pytest.mark.parametrize("state_backend", [QSimQuantumState, STIMQuantumState])
    def test_integrated(self, circuit_backend, model_backend, state_backend):
        if model_backend == PyGSTiNoiseModel and state_backend == STIMQuantumState:
            pytest.skip("PyGSTiNoiseModel cannot output STIM reps yet")
        
        code_5q = codepack_5_1_3.create_qec_code(circuit_backend=circuit_backend)

        # Define the physical qubit labels for our system here
        qubits = ["A0", "A1"] + [f"D{i+2}" for i in range(5)]

        if state_backend == QSimQuantumState:
            gaterep = GateRep.QSIM_SUPEROPERATOR
        else:
            gaterep = GateRep.STIM_CIRCUIT_STR

        ideal_model = codepack_5_1_3.create_ideal_model(qubits, gaterep=gaterep, model_backend=model_backend)

        state_type = state_backend
        patch_types = {"5Q": code_5q}

        # Stack
        # The "Init *" instructions will be generated by the QuantumProgram based on the values
        # of state_type and patch_types below
        stack = [
            ("Init State", None, (len(qubits),), {"qubit_labels": qubits}), # Autogenerated from state_type
            ("Init Patch 5Q", None, ("L0", qubits)), # Autogenerated from patch_types. Note that 5Q here must be a key into the patch_types dict below
            ("Non-FT Minus Prep", "L0"),
            ("Non-FT Logical X Measure", "L0")
        ]

        program = QuantumProgram(
            stack,
            default_noise_model=ideal_model,
            state_type=state_type,
            patch_types=patch_types,
            name="Prep minus, measure X"
        )

        # Run
        program.run()

        logical_outcomes = program.collect_shot_data('logical_measurement', -1)
        assert logical_outcomes == [1,]

    @pytest.mark.parametrize("format", ["json", "json.gz", "hdf5"])
    def test_program_serialization_parameterized(self, format):
        """Test QuantumProgram serialization with different formats using parameterization."""
        # Create a simple program for testing
        code_5q = codepack_5_1_3.create_qec_code(circuit_backend=ListPhysicalCircuit)
        qubits = ["A0", "A1"] + [f"D{i+2}" for i in range(5)]

        ideal_model = codepack_5_1_3.create_ideal_model(qubits, gaterep=GateRep.QSIM_SUPEROPERATOR, model_backend=DictNoiseModel)

        state_type = QSimQuantumState
        patch_types = {"5Q": code_5q}

        # Stack
        # The "Init *" instructions will be generated by the QuantumProgram based on the values
        # of state_type and patch_types below
        stack = [
            ("Init State", None, (len(qubits),), {"qubit_labels": qubits}), # Autogenerated from state_type
            ("Init Patch 5Q", None, ("L0", qubits)), # Autogenerated from patch_types. Note that 5Q here must be a key into the patch_types dict below
            ("Non-FT Minus Prep", "L0"),
            ("Non-FT Logical X Measure", "L0")
        ]

        program = QuantumProgram(
            stack,
            default_noise_model=ideal_model,
            state_type=state_type,
            patch_types=patch_types,
            name="Prep minus, measure X"
        )

        # Sanity check: program can run
        new_program = QuantumProgram.from_quantum_program(program)
        new_program.run()
        assert len(new_program.shot_histories) == 1  # Should have more frames after running

        # Test string serialization
        with NamedTemporaryFile("w+", suffix=f".{format}") as tempf:
            program.write(tempf.name)
            loaded_program = QuantumProgram.read(tempf.name)

        # Verify program structure is preserved
        assert len(loaded_program.shot_histories) == 0
        assert loaded_program.name == "Prep minus, measure X"
        assert len(loaded_program.instruction_stack) == len(stack)  # Stack should be preserved
        assert loaded_program.state_type == state_type
        assert len(loaded_program.patch_types) == len(patch_types)

        # Test that the loaded program can actually run (correctness check)
        loaded_program.run()
        assert len(loaded_program.shot_histories) == 1  # Should have more frames after running

        # Test file serialization
        with NamedTemporaryFile(suffix=f'.{format}') as f:
            loaded_program.write(f.name)
            loaded_program2 = QuantumProgram.read(f.name)

            # Verify program structure is preserved
            assert len(loaded_program2.shot_histories) == 1
            assert loaded_program2.name == "Prep minus, measure X"
            assert len(loaded_program2.instruction_stack) == len(stack)

            # Test that the loaded program can actually run (correctness check)
            # Only requesting 1 shot by default, so this shouldn't change it
            loaded_program2.run()
            assert len(loaded_program2.shot_histories) == 1

            # But now it should
            loaded_program2.run(num_shots=2)
            assert len(loaded_program2.shot_histories) == 2
