"""Tester for loqs.core.quantumprogram"""

import os
import pytest

# TODO: Rework to run with native backend only if failure to import
quantumsim = pytest.importorskip("quantumsim")
stim = pytest.importorskip("stim")

from loqs.backends import QSimQuantumState, STIMQuantumState
from loqs.core import QuantumProgram
from loqs.codepacks import codepack_trivial_counter as trivial_codepack

@pytest.mark.skipif(os.getenv("CI", "false") == "true", reason="Breaks GitHub runners?")
class TestQuantumProgram:

    # TODO: This is currently only an integrated test depending on a codepack
    # Make actual unit tests, and probably convert this to a codepack test
    
    # Note that tests will be labeled state-model-circuit with this stacking
    @pytest.mark.parametrize("state_backend", [QSimQuantumState, STIMQuantumState])
    def test_integrated(self, state_backend):
        # Use the trivial codepack for faster testing
        trivial_code = trivial_codepack.create_qec_code()

        # Define a simple qubit label for our trivial system
        qubits = ["Q0"]

        # For the trivial codepack, we don't need a complex model
        ideal_model = trivial_codepack.create_ideal_model(qubits)

        state_type = state_backend
        patch_types = {"Trivial": trivial_code}

        # Stack for a simple counter program
        # The "Init *" instructions will be generated by the QuantumProgram based on the values
        # of state_type and patch_types below
        stack = [
            ("Init State", None, (len(qubits),), {"qubit_labels": qubits}), # Autogenerated from state_type
            ("Init Patch Trivial", None, ("L0", qubits)), # Autogenerated from patch_types
            ("Init Counter", "L0", (), {"initial_value": 0}), # Initialize counter to 0
            ("Increment", "L0", (), {"increment_by": 1}), # Increment by 1
            ("Increment", "L0", (), {"increment_by": 2}), # Increment by 2
        ]

        program = QuantumProgram(
            stack,
            default_noise_model=ideal_model,
            state_type=state_type,
            patch_types=patch_types,
            name="Trivial counter test"
        )

        # Run
        program_results = program.run()

        # Check that the program ran successfully and has the expected number of frames
        assert len(program_results.shot_histories) == 1
        history = program_results.shot_histories[0]
        assert len(history) > 0  # Should have multiple frames from the instructions

    @pytest.mark.parametrize("format", ["json", "json.gz", "hdf5"])
    def test_program_serialization_parameterized(self, format, make_temp_path):
        """Test QuantumProgram serialization with different formats using parameterization."""
        # Create a simple program for testing using the trivial codepack
        trivial_code = trivial_codepack.create_qec_code()
        qubits = ["Q0"]

        ideal_model = trivial_codepack.create_ideal_model(qubits)

        state_type = QSimQuantumState
        patch_types = {"Trivial": trivial_code}

        # Stack for a simple counter program
        stack = [
            ("Init State", None, (len(qubits),), {"qubit_labels": qubits}), # Autogenerated from state_type
            ("Init Patch Trivial", None, ("L0", qubits)), # Autogenerated from patch_types
            ("Init Counter", "L0", (), {"initial_value": 0}), # Initialize counter to 0
            ("Increment", "L0", (), {"increment_by": 1}), # Increment by 1
        ]

        program = QuantumProgram(
            stack,
            default_noise_model=ideal_model,
            state_type=state_type,
            patch_types=patch_types,
            name="Trivial counter test"
        )

        # Sanity check: program can run
        new_program = QuantumProgram.from_quantum_program(program)
        new_program_results = new_program.run()
        assert len(new_program_results.shot_histories) == 1  # Should have more frames after running

        # Test string serialization
        with make_temp_path(suffix=f".{format}") as tempf_path:
            program.write(tempf_path)
            loaded_program = QuantumProgram.read(tempf_path)
            assert isinstance(loaded_program, QuantumProgram)

            # Verify program structure is preserved

            loaded_program_results = loaded_program.run()
            assert len(loaded_program_results.shot_histories) == 1  # Should have more frames after running
            assert loaded_program.name == "Trivial counter test"
            assert len(loaded_program.instruction_stack) == len(stack)  # Stack should be preserved
            assert loaded_program.state_type == state_type
            assert loaded_program.patch_types is not None
            assert len(loaded_program.patch_types) == len(patch_types)

        with make_temp_path(suffix=f'.{format}') as f_path:
            loaded_program.write(f_path)
            loaded_program2 = QuantumProgram.read(f_path)
            assert isinstance(loaded_program2, QuantumProgram)

            # Verify program structure is preserved
            loaded_program2_results = loaded_program2.run()
            assert len(loaded_program2_results.shot_histories) == 1
            assert loaded_program2.name == "Trivial counter test"
            assert len(loaded_program2.instruction_stack) == len(stack)

            # Test that the loaded program can actually run (correctness check)
            # Only requesting 1 shot by default, so this shouldn't change it
            loaded_program2_results2 = loaded_program2.run()
            assert len(loaded_program2_results2.shot_histories) == 1

            # But now it should
            loaded_program2_results3 = loaded_program2.run(num_shots=2)
            assert len(loaded_program2_results3.shot_histories) == 2
