"""TODO
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from copy import deepcopy
import textwrap
from typing import ParamSpec, Protocol, TypeAlias

from loqs.core import History, Frame
from loqs.core.history import HistoryCastableTypes


P = ParamSpec("P")

KwargDict: TypeAlias = dict[str, object]


class ApplyCallable(Protocol[P]):
    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> Frame: ...  # noqa


class MapQubitsCallable(Protocol[P]):
    def __call__(  # noqa
        self,
        qubit_mapping: Mapping[str, str],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> KwargDict: ...


def default_map_qubits(qubit_mapping: Mapping[str, str], **kwargs):
    # Assume nothing needs to be mapped in kwargs
    return kwargs


class Instruction:
    """TODO"""

    def __init__(
        self,
        apply_fn: ApplyCallable,
        dry_run_apply_fn: ApplyCallable | Sequence[str] | None = None,
        map_qubits_fn: MapQubitsCallable = default_map_qubits,
        data: Mapping[str, object] | None = None,
        name: str = "(Unnamed instruction)",
        parent: (
            object | None
        ) = None,  # TODO: Let be Instruction or InstructionStack
        fault_tolerant: bool | None = None,
    ) -> None:
        """TODO"""
        self.apply_fn = apply_fn

        if dry_run_apply_fn is None:
            dry_run_apply_fn = apply_fn
        if isinstance(dry_run_apply_fn, Sequence):
            assert all([isinstance(k, str) for k in dry_run_apply_fn])

            frame = Frame({k: "DRY_RUN" for k in dry_run_apply_fn})

            # TODO: Get signature from apply_fn
            def dummy_dry_run_fn() -> Frame:
                return frame

            dry_run_apply_fn = dummy_dry_run_fn
        self.dry_run_apply_fn = dry_run_apply_fn

        self.map_qubits_fn = map_qubits_fn

        if data is None:
            data = {}
        self.data = dict(data)

        self.name = name
        self.parent = parent
        self.fault_tolerant = fault_tolerant

    def __str__(self) -> str:
        s = f"Instruction {self.name}\n"
        s += "  Input parameter spec:\n"
        # sis = str(self.input_spec)
        # sis = textwrap.indent(sis, "    ")
        # s += sis
        # s += f"  Output frame keys: {self.output_spec}\n"
        s += "  Data:\n"
        for k, v in self.data.items():
            s += textwrap.indent(f"{k}: {v}", "    ")
            if not s.endswith("\n"):
                s += "\n"
        s += f"  Fault-tolerant: {self.fault_tolerant}\n"
        return s

    def apply(
        self, input: HistoryCastableTypes, dry_run: bool = False, *args
    ) -> Frame:
        """TODO"""
        # history = History.cast(input)

        # def collect_arg(param: InputParam):
        #     for source in param.sources:
        #         if source == "history":
        #             assert param.hist_key is not None
        #             assert param.hist_idxs is not None
        #             data = history.collect_data(
        #                 param.hist_key, param.hist_idxs
        #             )

        #             if (
        #                 isinstance(data, list)
        #                 and all([d is None for d in data])
        #                 or data is None
        #             ):
        #                 # We've failed to get anything
        #                 # Try next source
        #                 continue

        #             return data
        #         elif source == "default":
        #             if param.key not in self.defaults:
        #                 # We won't be able to retrieve
        #                 # Try next source
        #                 continue

        #             return copy.deepcopy(self.defaults[param.key])
        #         elif source == "label":
        #             if param.position < len(args):
        #                 return args[param.position]

        #             if param.key not in kwargs:
        #                 # We won't be able to retrieve
        #                 # Try next source
        #                 continue

        #             return kwargs[param.key]
        #         else:
        #             raise ValueError("Invalid InputParam source")

        #     # If we get here, we've failed to get any data
        #     raise ValueError(f"Failed to collect {param}")

        # Pull necessary data from input spec
        # If "history", pull from history generated by input
        # If "default", pull from Instruction.default_kwargs
        # If "label", pull from passed in kwargs (i.e. from InstructionLabel)
        # Multiple can be specified, try in order with earlier getting precedence
        # apply_args = [collect_arg(param) for param in self.input_spec]

        if dry_run:
            applied_frame = self.dry_run_apply_fn(*args)
        else:
            applied_frame = self.apply_fn(*args)

        output_frame = applied_frame.update(
            {
                "instruction": self,
                "instruction_args": args,
            },
            f"{self.name} result",
        )
        return output_frame

    def copy(self) -> Instruction:
        return Instruction(
            self.apply_fn,
            # self.input_spec,
            # self.output_spec,
            self.dry_run_apply_fn,
            self.map_qubits_fn,
            self.data.copy(),
            self.name,
            self.parent,
            self.fault_tolerant,
        )

    def map_qubits(
        self: Instruction, qubit_mapping: Mapping[str, str]
    ) -> Instruction:
        """TODO"""
        new_instruction = self.copy()
        # Map qubits on all data
        new_kwargs = self.map_qubits_fn(qubit_mapping, **self.data)
        assert all(
            [k in new_kwargs for k in self.data]
        ), "map_qubits_fn did not output all expected keys"
        new_instruction.data = new_kwargs
        return new_instruction
