"""TODO
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import ParamSpec, Protocol, TypeAlias

from loqs.core import History, Frame
from loqs.core.history import HistoryCastableTypes
from loqs.core.instructions import InputSpec
from loqs.core.instructions.inputspec import InputSpecCastableTypes


P = ParamSpec("P")

KwargDict: TypeAlias = dict[str, object]


class ApplyCallable(Protocol[P]):
    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> Frame: ...  # noqa


class MapQubitsCallable(Protocol[P]):
    def __call__(  # noqa
        self,
        qubit_mapping: Mapping[str, str],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> KwargDict: ...


def default_map_qubits(qubit_mapping: Mapping[str, str], **kwargs):
    # Assume nothing needs to be mapped in kwargs
    return kwargs


class Instruction:
    """TODO"""

    def __init__(
        self,
        apply_fn: ApplyCallable,
        input_spec: InputSpecCastableTypes,
        output_spec: Sequence[str],
        default_kwargs: Mapping | None = None,
        map_qubits_fn: MapQubitsCallable = default_map_qubits,
        name: str = "(Unnamed instruction)",
        parent: (
            object | None
        ) = None,  # TODO: Figure out how to allow InstructionStack without circ dep
        fault_tolerant: bool | None = None,
    ) -> None:
        """TODO"""
        self.apply_fn = apply_fn
        self.input_spec = InputSpec.cast(input_spec)
        self.output_spec = list(output_spec)

        self.map_qubits_fn = map_qubits_fn
        if default_kwargs is None:
            default_kwargs = {}
        self.default_kwargs = dict(default_kwargs)

        self.name = name
        self.parent = parent
        self.fault_tolerant = fault_tolerant

    def apply(
        self, input: HistoryCastableTypes, dry_run: bool = False, **kwargs
    ) -> Frame:
        """TODO"""
        history = History.cast(input)

        # Pull necessary data from input spec
        # If "history", pull from history generated by input
        # If "default", pull from Instruction.default_kwargs
        # If "label", pull from passed in kwargs (i.e. from InstructionLabel)
        # Multiple can be specified, try in order with earlier getting precedence
        apply_kwargs = {}
        for param in self.input_spec:
            key = param.kwargs_key
            for source in param.sources:
                if key in apply_kwargs:
                    # Higher-precedence source must have gotten it
                    continue

                if source == "history":
                    data = history.collect_data(
                        param.hist_key, param.hist_idxs
                    )

                    if any([d is not None for d in data]):
                        # We got something from the history
                        apply_kwargs[key] = data
                elif source == "default":
                    if key in self.default_kwargs:
                        apply_kwargs[key] = self.default_kwargs[key]
                elif source == "label":
                    if key in kwargs:
                        apply_kwargs[key] = kwargs[key]
                else:
                    raise ValueError("Invalid InputParam source")

        # Check we got something for every desired kwarg
        needed_keys = set(self.input_spec.kwarg_keys)
        found_keys = set(apply_kwargs.keys())
        missing_keys = needed_keys.difference(found_keys)
        assert (
            len(missing_keys) == 0
        ), f"Failed to load some kwargs: {missing_keys} "

        if dry_run:
            applied_frame = Frame({k: None for k in self.output_spec})
        else:
            applied_frame = self.apply_fn(**apply_kwargs)

        assert all(
            [k in applied_frame for k in self.output_spec]
        ), "apply_fn did not output all expected keys"

        output_frame = applied_frame.update(
            {"instruction": self}, f"{self.name} result"
        )
        return output_frame

    def copy(self) -> Instruction:
        return Instruction(
            self.apply_fn,
            self.input_spec,
            self.output_spec,
            self.default_kwargs.copy(),
            self.map_qubits_fn,
            self.name,
            self.parent,
            self.fault_tolerant,
        )

    def map_qubits(
        self: Instruction, qubit_mapping: Mapping[str, str]
    ) -> Instruction:
        """TODO"""
        new_instruction = self.copy()
        # Map qubits on all data
        new_kwargs = self.map_qubits_fn(qubit_mapping, **self.default_kwargs)
        assert all(
            [k in new_kwargs for k in self.default_kwargs]
        ), "map_qubits_fn did not output all expected keys"
        new_instruction.default_kwargs = new_kwargs
        return new_instruction
