"""Regression test for `tests/backends/fixtures/reps_v2.{json,h5}`.

Unlike `test_legacy.py` (the regression oracle for the *v1 -> v2* decode
redirect), these fixtures aren't exercising any compatibility machinery
today -- they're a frozen, byte-for-byte snapshot of the current
(`SERIALIZATION_VERSION` 2) `GateRep`/`InstrumentRep` format, generated by
`generate_reps_fixtures_v2.py`. Their value is entirely prospective: once
a future version bump needs its own legacy-decode redirect, these bytes
are already on hand as the "known-good v2 file" to validate it against,
the same role `reps_v1.{json,h5}` played for this version's own
`RepTuple` removal.
"""

import json
from pathlib import Path

import h5py
import numpy as np
import pytest

from loqs.backends.reps import (
    KrausGateRep,
    OutcomeOperationDictInstrumentRep,
    PTMGateRep,
    ProbabilisticStimGateRep,
    QSimSuperopGateRep,
    StimCircuitGateRep,
    StimCircuitInstrumentRep,
    UnitaryGateRep,
    ZBasisPrePostInstrumentRep,
    ZBasisProjectionInstrumentRep,
)
from loqs.internal.serializable import Serializable

FIXTURES_DIR = Path(__file__).parent.parent / "fixtures"

EXPECTED_CLASSES = {
    "GATEREP_UNITARY": UnitaryGateRep,
    "GATEREP_PTM": PTMGateRep,
    "GATEREP_QSIM_SUPEROPERATOR": QSimSuperopGateRep,
    "GATEREP_STIM_CIRCUIT_STR": StimCircuitGateRep,
    "GATEREP_PROBABILISTIC_STIM_OPERATIONS": ProbabilisticStimGateRep,
    "GATEREP_KRAUS_OPERATORS": KrausGateRep,
    "INSTRUMENTREP_ZBASIS_PROJECTION": ZBasisProjectionInstrumentRep,
    "INSTRUMENTREP_ZBASIS_PRE_POST_OPERATIONS": ZBasisPrePostInstrumentRep,
    "INSTRUMENTREP_ZBASIS_OUTCOME_OPERATION_DICT": (
        OutcomeOperationDictInstrumentRep
    ),
    "INSTRUMENTREP_STIM_CIRCUIT_STR": StimCircuitInstrumentRep,
}


class TestRepsV2FixtureRoundTrip:
    @pytest.fixture(params=["json", "hdf5"])
    def decoded(self, request):
        if request.param == "json":
            with open(FIXTURES_DIR / "reps_v2.json") as f:
                return Serializable.decode(json.load(f), format="json")
        else:
            with h5py.File(FIXTURES_DIR / "reps_v2.h5", "r") as f:
                return Serializable.decode(f["root"], format="hdf5")

    def test_all_members_present_with_correct_class(self, decoded):
        assert set(decoded.keys()) == set(EXPECTED_CLASSES.keys())
        for name, expected_cls in EXPECTED_CLASSES.items():
            rep = decoded[name]
            assert type(rep) is expected_cls, (
                f"{name} decoded to {type(rep).__name__}, expected "
                f"{expected_cls.__name__}"
            )
            assert rep.qubit_labels == ("Q0",)

    def test_flat_payloads_round_trip(self, decoded):
        assert decoded["GATEREP_STIM_CIRCUIT_STR"].circuit_str == "X 0"
        assert decoded["INSTRUMENTREP_STIM_CIRCUIT_STR"].circuit_str == "M 0"
        assert isinstance(decoded["GATEREP_UNITARY"].unitary, np.ndarray)
        assert decoded["GATEREP_UNITARY"].unitary.shape == (2, 2)
        kraus = decoded["GATEREP_KRAUS_OPERATORS"].kraus_operators
        assert len(kraus) == 2

    def test_nested_pre_post_operations_round_trip(self, decoded):
        rep = decoded["INSTRUMENTREP_ZBASIS_PRE_POST_OPERATIONS"]
        assert rep.reset == 0
        assert isinstance(rep.pre_op, UnitaryGateRep)
        assert isinstance(rep.post_op, UnitaryGateRep)

    def test_module_and_class_metadata(self):
        """Pin down the (module, class, version) metadata this fixture
        records, not just its round-trip behavior -- this is exactly what
        a future decode redirect for these classes would need to match."""
        with open(FIXTURES_DIR / "reps_v2.json") as f:
            raw = json.load(f)
        entry = raw["items"]["GATEREP_UNITARY"]
        assert entry["module"] == "loqs.backends.reps.gatereps"
        assert entry["class"] == "UnitaryGateRep"
        assert entry["version"] == 2
