"""Tester for loqs.backends.reps.legacy

This is the regression oracle for LoQS#72's decode-only compatibility
shim: `tests/backends/fixtures/reps_v1.{json,h5}` are frozen, pre-refactor
bytes (generated by `generate_reps_fixtures.py` from the old `RepTuple`/
`GateRep`/`InstrumentRep` enum-based code, before this refactor), and
decoding them against the *current* code is the only way to confirm old
`.json`/`.h5` files continue to load correctly.
"""

import json
from pathlib import Path

import h5py
import numpy as np
import pytest

from loqs.backends.reps import (
    GateRep,
    InstrumentRep,
    KrausGateRep,
    PTMGateRep,
    ProbabilisticStimGateRep,
    QSimSuperopGateRep,
    RepTuple,
    StimCircuitGateRep,
    StimCircuitInstrumentRep,
    UnitaryGateRep,
    ZBasisOutcomeOperationDictInstrumentRep,
    ZBasisPrePostInstrumentRep,
    ZBasisProjectionInstrumentRep,
)
from loqs.backends.reps.legacy import (
    upgrade_legacy_gaterep_tag,
    upgrade_legacy_instrumentrep_tag,
)
from loqs.internal.serializable import Serializable

FIXTURES_DIR = Path(__file__).parent.parent / "fixtures"


class TestRepTupleConstructionRaises:
    def test_direct_construction_raises_type_error(self):
        with pytest.raises(TypeError, match="RepTuple is deprecated"):
            RepTuple("X 0", ("Q0",), None)

    def test_construction_raises_regardless_of_arguments(self):
        with pytest.raises(TypeError, match="RepTuple is deprecated"):
            RepTuple()


class TestRepsFixtureRoundTrip:
    """Round-trip `tests/backends/fixtures/reps_v1.{json,h5}` (generated
    pre-refactor by `generate_reps_fixtures.py`) to confirm every old
    `GateRep`/`InstrumentRep` member -- including the two nested-`RepTuple`
    cases -- decodes directly to the correct new concrete class, never to
    a `RepTuple` instance."""

    EXPECTED_CLASSES = {
        "GATEREP_UNITARY": UnitaryGateRep,
        "GATEREP_PTM": PTMGateRep,
        "GATEREP_QSIM_SUPEROPERATOR": QSimSuperopGateRep,
        "GATEREP_STIM_CIRCUIT_STR": StimCircuitGateRep,
        "GATEREP_PROBABILISTIC_STIM_OPERATIONS": ProbabilisticStimGateRep,
        "GATEREP_KRAUS_OPERATORS": KrausGateRep,
        "INSTRUMENTREP_ZBASIS_PROJECTION": ZBasisProjectionInstrumentRep,
        "INSTRUMENTREP_ZBASIS_PRE_POST_OPERATIONS": ZBasisPrePostInstrumentRep,
        "INSTRUMENTREP_ZBASIS_OUTCOME_OPERATION_DICT": (
            ZBasisOutcomeOperationDictInstrumentRep
        ),
        "INSTRUMENTREP_STIM_CIRCUIT_STR": StimCircuitInstrumentRep,
    }

    @pytest.fixture(params=["json", "hdf5"])
    def decoded(self, request):
        if request.param == "json":
            with open(FIXTURES_DIR / "reps_v1.json") as f:
                return Serializable.decode(json.load(f), format="json")
        else:
            with h5py.File(FIXTURES_DIR / "reps_v1.h5", "r") as f:
                return Serializable.decode(f["root"], format="hdf5")

    def test_all_members_present_with_correct_class(self, decoded):
        assert set(decoded.keys()) == set(self.EXPECTED_CLASSES.keys())
        for name, expected_cls in self.EXPECTED_CLASSES.items():
            rep = decoded[name]
            assert type(rep) is expected_cls, (
                f"{name} decoded to {type(rep).__name__}, expected "
                f"{expected_cls.__name__}"
            )
            assert not isinstance(rep, RepTuple)
            assert rep.qubit_labels == ("Q0",)

    def test_flat_gate_rep_payloads_round_trip(self, decoded):
        assert decoded["GATEREP_STIM_CIRCUIT_STR"].circuit_str == "X 0"
        probs = decoded["GATEREP_PROBABILISTIC_STIM_OPERATIONS"].operations
        assert tuple(probs) == (("X 0", 0.5), ("Y 0", 0.5))
        kraus = decoded["GATEREP_KRAUS_OPERATORS"].kraus_operators
        assert len(kraus) == 2
        for op, prob in kraus:
            assert isinstance(op, np.ndarray)
            assert op.shape == (2, 2)
            assert prob is None
        assert isinstance(decoded["GATEREP_UNITARY"].unitary, np.ndarray)
        assert decoded["GATEREP_UNITARY"].unitary.shape == (2, 2)
        assert decoded["GATEREP_PTM"].ptm.shape == (4, 4)
        assert decoded["GATEREP_QSIM_SUPEROPERATOR"].superop.shape == (4, 4)

    def test_nested_pre_post_operations_round_trip(self, decoded):
        rep = decoded["INSTRUMENTREP_ZBASIS_PRE_POST_OPERATIONS"]
        assert rep.reset == 0
        # NOTE: `include_outcome` decodes as plain `int` (1), not `bool`
        # (True) -- see test_bool_payloads_round_trip_as_bool below for
        # why -- so compare by value, not identity/type.
        assert rep.include_outcome == True  # noqa: E712
        assert isinstance(rep.pre_op, UnitaryGateRep)
        assert isinstance(rep.post_op, UnitaryGateRep)
        assert rep.pre_op.qubit_labels == ("Q0",)
        assert rep.post_op.qubit_labels == ("Q0",)

    def test_nested_outcome_operation_dict_round_trip(self, decoded, request):
        """NOTE: JSON round-trips the `{0: ..., 1: ...}` outcome dict's keys
        as *strings* (`"0"`, `"1"`), not ints -- an inherent JSON limitation
        (object keys are always strings), not a LoQS-specific bug. HDF5
        preserves the original int keys.
        """
        rep = decoded["INSTRUMENTREP_ZBASIS_OUTCOME_OPERATION_DICT"]
        assert rep.include_outcome == True  # noqa: E712
        if "json" in request.node.callspec.id:
            assert set(rep.outcome_ops.keys()) == {"0", "1"}
            outcome_0, outcome_1 = rep.outcome_ops["0"], rep.outcome_ops["1"]
        else:
            assert set(rep.outcome_ops.keys()) == {0, 1}
            outcome_0, outcome_1 = rep.outcome_ops[0], rep.outcome_ops[1]
        assert isinstance(outcome_0, PTMGateRep)
        assert isinstance(outcome_1, QSimSuperopGateRep)

    def test_module_and_class_metadata(self):
        """The (module, class) metadata this fixture records is exactly the
        mechanism the legacy-decode shim depends on -- pin it down
        explicitly rather than only testing round-trip behavior
        end-to-end. `reps/__init__.py` re-exporting `RepTuple`/`GateRep`
        at the top level of `loqs.backends.reps` is what keeps this
        resolvable even though `reps.py` became a subpackage."""
        with open(FIXTURES_DIR / "reps_v1.json") as f:
            raw = json.load(f)
        entry = raw["items"]["GATEREP_UNITARY"]
        assert entry["module"] == "loqs.backends.reps"
        assert entry["class"] == "RepTuple"
        reptype_entry = entry["reptype"]
        assert reptype_entry["module"] == "loqs.backends.reps"
        assert reptype_entry["class"] == "GateRep"


class TestLegacyGaterepValueUpgrade:
    """Directly exercise `upgrade_legacy_gaterep_tag`, used by
    `DictNoiseModel._from_decoded_attrs` to translate old bare
    `GateRep`/`InstrumentRep` enum-member tags (as found in `_gatereps`/
    `_instreps`, never wrapped in a `RepTuple`) into modern classes."""

    def test_passthrough_for_non_legacy_values(self):
        assert upgrade_legacy_gaterep_tag(UnitaryGateRep) is UnitaryGateRep
        assert upgrade_legacy_gaterep_tag("not a legacy tag") == "not a legacy tag"

    def test_upgrades_every_legacy_gaterep_value(self):
        from loqs.backends.reps.legacy import (
            _LegacyGateRepValue,
            upgrade_legacy_gaterep_tag,
        )

        expected = {
            _LegacyGateRepValue.UNITARY: UnitaryGateRep,
            _LegacyGateRepValue.PTM: PTMGateRep,
            _LegacyGateRepValue.QSIM_SUPEROPERATOR: QSimSuperopGateRep,
            _LegacyGateRepValue.STIM_CIRCUIT_STR: StimCircuitGateRep,
            _LegacyGateRepValue.PROBABILISTIC_STIM_OPERATIONS: (
                ProbabilisticStimGateRep
            ),
            _LegacyGateRepValue.KRAUS_OPERATORS: KrausGateRep,
        }
        for legacy_value, expected_cls in expected.items():
            assert upgrade_legacy_gaterep_tag(legacy_value) is expected_cls

    def test_upgrades_every_legacy_instrumentrep_value(self):
        from loqs.backends.reps.legacy import (
            _LegacyInstrumentRepValue,
            upgrade_legacy_gaterep_tag,
        )

        expected = {
            _LegacyInstrumentRepValue.ZBASIS_PROJECTION: (
                ZBasisProjectionInstrumentRep
            ),
            _LegacyInstrumentRepValue.ZBASIS_PRE_POST_OPERATIONS: (
                ZBasisPrePostInstrumentRep
            ),
            _LegacyInstrumentRepValue.ZBASIS_OUTCOME_OPERATION_DICT: (
                ZBasisOutcomeOperationDictInstrumentRep
            ),
            _LegacyInstrumentRepValue.STIM_CIRCUIT_STR: (
                StimCircuitInstrumentRep
            ),
        }
        for legacy_value, expected_cls in expected.items():
            assert upgrade_legacy_gaterep_tag(legacy_value) is expected_cls

    def test_bare_int_assumed_gaterep_family(self):
        """`SERIALIZATION_VERSION` 0 (the original, pre-HDF5 JSON format)
        encoded `_gatereps` entries as bare `int`s with no `(module,
        class)` metadata at all to disambiguate `GateRep` from
        `InstrumentRep` -- `upgrade_legacy_gaterep_tag` is only ever
        called on `_gatereps` entries, so a bare int must be resolved as a
        `GateRep`-family legacy value."""
        assert upgrade_legacy_gaterep_tag(1) is UnitaryGateRep
        assert upgrade_legacy_gaterep_tag(6) is KrausGateRep

    def test_bare_int_instrumentrep_family(self):
        """`upgrade_legacy_instrumentrep_tag` is the `_instreps`-context
        equivalent of `upgrade_legacy_gaterep_tag` -- a bare int here must
        resolve as an `InstrumentRep`-family legacy value instead."""
        assert upgrade_legacy_instrumentrep_tag(1) is ZBasisProjectionInstrumentRep
        assert upgrade_legacy_instrumentrep_tag(4) is StimCircuitInstrumentRep

    def test_upgrade_legacy_instrumentrep_tag_passthrough(self):
        assert (
            upgrade_legacy_instrumentrep_tag(ZBasisProjectionInstrumentRep)
            is ZBasisProjectionInstrumentRep
        )

    def test_upgrade_legacy_instrumentrep_tag_handles_legacy_tags_too(self):
        """Both helper functions handle either legacy-tag enum type --
        only the bare-int fallback actually depends on which function is
        called."""
        from loqs.backends.reps.legacy import _LegacyGateRepValue

        assert (
            upgrade_legacy_instrumentrep_tag(_LegacyGateRepValue.UNITARY)
            is UnitaryGateRep
        )

    def test_stim_circuit_str_disambiguated_between_gate_and_instrument(self):
        """`GateRep.STIM_CIRCUIT_STR` and `InstrumentRep.STIM_CIRCUIT_STR`
        coincidentally shared the same integer value (4) in the
        pre-refactor enums -- confirm the two separate legacy-tag enum
        types (rather than shared integer values) correctly disambiguate
        which one a given tag came from."""
        from loqs.backends.reps.legacy import (
            _LegacyGateRepValue,
            _LegacyInstrumentRepValue,
            upgrade_legacy_gaterep_tag,
        )

        assert _LegacyGateRepValue.STIM_CIRCUIT_STR.value == 4
        assert _LegacyInstrumentRepValue.STIM_CIRCUIT_STR.value == 4
        assert (
            upgrade_legacy_gaterep_tag(_LegacyGateRepValue.STIM_CIRCUIT_STR)
            is StimCircuitGateRep
        )
        assert (
            upgrade_legacy_gaterep_tag(
                _LegacyInstrumentRepValue.STIM_CIRCUIT_STR
            )
            is StimCircuitInstrumentRep
        )


class TestLegacyValueDecoding:
    """Directly exercise `GateRep._from_decoded_attrs`/
    `InstrumentRep._from_decoded_attrs`'s legacy-tag special-casing,
    without going through a full `RepTuple`-wrapped fixture."""

    def test_gaterep_class_decodes_to_legacy_tag(self):
        from loqs.backends.reps.legacy import _LegacyGateRepValue

        result = GateRep._from_decoded_attrs({"value": 1})
        assert result is _LegacyGateRepValue.UNITARY

    def test_instrumentrep_class_decodes_to_legacy_tag(self):
        from loqs.backends.reps.legacy import _LegacyInstrumentRepValue

        result = InstrumentRep._from_decoded_attrs({"value": 1})
        assert result is _LegacyInstrumentRepValue.ZBASIS_PROJECTION

    def test_concrete_gaterep_subclass_does_not_use_legacy_path(self):
        """A concrete subclass's `_from_decoded_attrs` (inherited from
        `GateRep`, unmodified) should fall through to normal
        `Serializable`-style construction, not the legacy-tag branch,
        since `cls is GateRep` is only true for the literal abstract
        base."""
        result = UnitaryGateRep._from_decoded_attrs(
            {"unitary": np.eye(2), "qubits": ("Q0",)}
        )
        assert isinstance(result, UnitaryGateRep)
        assert np.array_equal(result.unitary, np.eye(2))
        assert result.qubit_labels == ("Q0",)

    def test_concrete_instrumentrep_subclass_does_not_use_legacy_path(self):
        """Same as above, but for `InstrumentRep`'s equivalent
        `_from_decoded_attrs` override -- a concrete subclass falls
        through to normal `Serializable`-style construction rather than
        the legacy-tag branch, since `cls is InstrumentRep` is only true
        for the literal abstract base."""
        result = ZBasisProjectionInstrumentRep._from_decoded_attrs(
            {"reset": 0, "include_outcome": True, "qubits": ("Q0",)}
        )
        assert isinstance(result, ZBasisProjectionInstrumentRep)
        assert result.reset == 0
        assert result.include_outcome is True
        assert result.qubit_labels == ("Q0",)


class TestMisformedLegacyDecode:
    def test_reptuple_from_decoded_attrs_rejects_unrecognized_reptype(self):
        from loqs.internal.serializable import MisformedDecodableError

        with pytest.raises(MisformedDecodableError):
            RepTuple._from_decoded_attrs(
                {"rep": None, "qubits": (), "reptype": "not a legacy tag"}
            )
