"""Tester for loqs.codepacks.codepack_7_1_3_quantinuum2021"""

import pytest

from loqs.backends import GateRep, PyGSTiPhysicalCircuit, ListPhysicalCircuit, PyGSTiNoiseModel, DictNoiseModel, QSimQuantumState, STIMQuantumState
from loqs.core import Frame, Instruction, QuantumProgram
from loqs.codepacks import codepack_7_1_3_quantinuum2021 as codepack_steane
from loqs.core.recordables import MeasurementOutcomes
from loqs.tools import fttools

class TestSteaneCodepack:

    @staticmethod
    def _create_program(circuit_backend, model_backend, state_backend):
        code_steane = codepack_steane.create_qec_code(circuit_backend=circuit_backend)

        # Define the physical qubit labels for our system here
        qubits = ["A0", "A1", "A2"] + [f"D{i+3}" for i in range(7)]

        if state_backend == QSimQuantumState:
            gaterep = GateRep.QSIM_SUPEROPERATOR
        else:
            gaterep = GateRep.STIM_CIRCUIT_STR

        ideal_model = codepack_steane.create_ideal_model(qubits, gaterep=gaterep, model_backend=model_backend)

        state_type = state_backend
        patch_types = {"Steane": code_steane}

        # Stack
        # The "Init *" instructions will be generated by the QuantumProgram based on the values
        # of state_type and patch_types below
        stack = [
            ("Init State", None, (len(qubits),), {"qubit_labels": qubits}), # Autogenerated from state_type
            ("Init Patch Steane", None, ("L0", qubits)), # Autogenerated from patch_types. Note that 5Q here must be a key into the patch_types dict below
            ("Non-FT Zero Prep", "L0"),
            ("FT Logical Z Measure", "L0")
        ]

        return QuantumProgram(
            stack,
            default_noise_model=ideal_model,
            state_type=state_type,
            patch_types=patch_types,
            name="Prep zero, measure Z"
        )

    @classmethod
    def setup_class(cls):
        cls.code_steane = codepack_steane.create_qec_code(circuit_backend=PyGSTiPhysicalCircuit)
        cls.program = cls._create_program(PyGSTiPhysicalCircuit, PyGSTiNoiseModel, QSimQuantumState)
        cls.qubits = ["A0", "A1", "A2"] + [f"D{i+3}" for i in range(7)]
    
    # Note that tests will be labeled stack_outcome-state-model-circuit with this stacking
    @pytest.mark.parametrize("circuit_backend", [PyGSTiPhysicalCircuit, ListPhysicalCircuit])
    @pytest.mark.parametrize("model_backend", [PyGSTiNoiseModel, DictNoiseModel])
    @pytest.mark.parametrize("state_backend", [QSimQuantumState, STIMQuantumState])
    @pytest.mark.parametrize("stack_outcome", [
        ([("FT Logical Z Measure", "L0")], 0),
        ([("X", "L0"), ("FT Logical Z Measure", "L0")], 1),
        ([("H", "L0"), ("FT Logical X Measure", "L0")], 0),
        ([("H", "L0"), ("Z", "L0"), ("FT Logical X Measure", "L0")], 1),
    ])
    def test_nonft_workflow(self, circuit_backend, model_backend, state_backend, stack_outcome):
        if model_backend == PyGSTiNoiseModel and state_backend == STIMQuantumState:
            pytest.skip("PyGSTiNoiseModel cannot output STIM reps yet")
        
        ref_program = self._create_program(circuit_backend, model_backend, state_backend)

        stack = [
            ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}),
            ("Init Patch Steane", None, ("L0",self.qubits)),
            ("Non-FT Zero Prep", "L0"),
        ]
        stack += stack_outcome[0]

        program = QuantumProgram.from_quantum_program(ref_program, stack)
        program.run()
        assert program.collect_shot_data("logical_measurement", -1)[0] == stack_outcome[1]

    # Note that tests will be labeled stack_outcome-state-model-circuit with this stacking
    @pytest.mark.parametrize("circuit_backend", [PyGSTiPhysicalCircuit, ListPhysicalCircuit])
    @pytest.mark.parametrize("model_backend", [PyGSTiNoiseModel, DictNoiseModel])
    @pytest.mark.parametrize("state_backend", [QSimQuantumState, STIMQuantumState])
    @pytest.mark.parametrize("stack_outcome", [
        ([("FT Logical Z Measure", "L0")], 0),
        ([("X", "L0"), ("Adaptive QEC", "L0"), ("FT Logical Z Measure", "L0")], 1),
    ])
    def test_ft_workflow(self, circuit_backend, model_backend, state_backend, stack_outcome):
        if model_backend == PyGSTiNoiseModel and state_backend == STIMQuantumState:
            pytest.skip("PyGSTiNoiseModel cannot output STIM reps yet")
        ref_program = self._create_program(circuit_backend, model_backend, state_backend)
        
        stack_ft = [
            ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}),
            ("Init Patch Steane", None, ("L0",self.qubits)),
            ("FT Zero Prep", "L0")
        ]
        stack_ft += stack_outcome[0]

        program = QuantumProgram.from_quantum_program(ref_program, stack_ft)
        program.run()
        assert program.collect_shot_data("logical_measurement", -1)[0] == stack_outcome[1]
    

    def _test_program(self, program, key, idx):
        noise_injected_programs = fttools.build_discrete_error_injection_programs(
            base_program=program,
            instruction_to_analyze=self.code_steane.instructions[key],
            stack_idx_to_modify=idx,
            error_circuit_labels=["Gxpi", "Gypi", "Gzpi"],
        )

        failed = fttools.run_discrete_error_injected_programs(
            noise_injected_programs,
            [("logical_measurement", -1)],
            [1],
        )
        return len(failed) == 0
    
    # def test_all_discrete_errors_prep(self):
    #     stack_ftprep = [
    #         ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}),
    #         ("Init Patch 5Q", None, ("L0", self.qubits)),
    #         ("Non-FT Minus Prep", "L0"), # Make this one error, RUS should catch and rerun it
    #         ("FT Minus Prep", "L0"),
    #         ("FT Logical X Measure", "L0")
    #     ]

    #     program_ftprep = QuantumProgram.from_quantum_program(self.program, stack_ftprep, name="FT Prep -, FT measure X")
    #     assert self._test_program(program_ftprep, "Non-FT Minus Prep", 2)

    # def test_all_discrete_errors_meas(self):
    #     ## PART I
    #     stack_ftmeas_partI = [
    #         ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}), # Autogenerated from state_type
    #         ("Init Patch 5Q", None, ("L0", self.qubits)), # Autogenerated from patch_types. Note that 5Q here must be a key into the patch_types dict below
    #         ("FT Minus Prep", "L0"),
    #         ("FT Logical X Measure Part I Circuit", "L0"),
    #         ("FT Logical X Measure Part I Feed-Forward", "L0"),
    #     ]

    #     program_ftmeas_partI = QuantumProgram.from_quantum_program(self.program, stack_ftmeas_partI, name="FT Prep -, non-FT measure X")
    #     assert self._test_program(program_ftmeas_partI, "FT Logical X Measure Part I Circuit", 3)

    #     ## PART II
    #     def ideal_partI_apply_fn():
    #         return Frame({"F1": 0, "inferred_M1": 1})

    #     ideal_partI = Instruction(
    #         ideal_partI_apply_fn,
    #         serialized_apply_fn="" # Hack, we won't need to serialize
    #     )

    #     stack_ftmeas_partII = [
    #         ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}), # Autogenerated from state_type
    #         ("Init Patch 5Q", None, ("L0", self.qubits)), # Autogenerated from patch_types. Note that 5Q here must be a key into the patch_types dict below
    #         ("FT Minus Prep", "L0"),
    #         ("FT Logical X Measure Part I Circuit", "L0"),
    #         ("Ideal Part I Feed-Forward", None), # Forward reference to global instruction
    #         ("FT Logical X Measure Part II Circuit", "L0"),
    #         ("FT Logical X Measure Part II Feed-Forward", "L0"),
    #     ]

    #     program_ftmeas_partII = QuantumProgram.from_quantum_program(
    #         self.program,
    #         stack_ftmeas_partII,
    #         global_instructions={"Ideal Part I Feed-Forward": ideal_partI},
    #         name="FT Prep -, FT measure X"
    #     )
    #     assert self._test_program(program_ftmeas_partII, "FT Logical X Measure Part II Circuit", 5)

    #     ## PART III
    #     def ideal_partII_apply_fn():
    #         return Frame({"F2": 0, "inferred_M2": 1})

    #     ideal_partII = Instruction(
    #         ideal_partII_apply_fn,
    #         serialized_apply_fn="" # Hack, we won't need to serialize
    #     )

    #     stack_ftmeas_partIII = [
    #         ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}), # Autogenerated from state_type
    #         ("Init Patch 5Q", None, ("L0", self.qubits)), # Autogenerated from patch_types. Note that 5Q here must be a key into the patch_types dict below
    #         ("FT Minus Prep", "L0"),
    #         ("FT Logical X Measure Part I Circuit", "L0"),
    #         ("Ideal Part I Feed-Forward", None), # Forward reference to global instruction
    #         ("FT Logical X Measure Part II Circuit", "L0"),
    #         ("Ideal Part II Feed-Forward", None), # Forward reference to global instruction
    #         ("FT Logical X Measure Part III Circuit", "L0"),
    #         ("FT Logical X Measure Part III Feed-Forward", "L0"),
    #     ]

    #     program_ftmeas_partIII = QuantumProgram.from_quantum_program(
    #         self.program,
    #         stack_ftmeas_partIII,
    #         global_instructions={
    #             "Ideal Part I Feed-Forward": ideal_partI,
    #             "Ideal Part II Feed-Forward": ideal_partII
    #         },
    #         name="FT Prep -, FT measure X"
    #     )
    #     assert self._test_program(program_ftmeas_partIII, "FT Logical X Measure Part III Circuit", 7)

    # def test_all_discrete_errors_QEC(self):
    #     # XZZXI
    #     stack_ftqec1 = [
    #         ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}), # Autogenerated from state_type
    #         ("Init Patch 5Q", None, ("L0", self.qubits)), # Autogenerated from patch_types. Note that 5Q here must be a key into the patch_types dict below
    #         ("FT Minus Prep", "L0"),
    #         ("Flagged XZZXI Check", "L0"),
    #         ("Flagged XZZXI Feed-Forward", "L0"),
    #         ("FT Logical X Measure", "L0")
    #     ]

    #     program_ftqec1 = QuantumProgram.from_quantum_program(
    #         self.program,
    #         stack_ftqec1,
    #         name="FT Prep -, QEC, FT measure X"
    #     )
    #     assert self._test_program(program_ftqec1, "Flagged XZZXI Check", 3)

    #     ## IXZZX
    #     stack_ftqec2 = [
    #         ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}), # Autogenerated from state_type
    #         ("Init Patch 5Q", None, ("L0", self.qubits)), # Autogenerated from patch_types. Note that 5Q here must be a key into the patch_types dict below
    #         ("FT Minus Prep", "L0"),
    #         ("Flagged IXZZX Check", "L0"),
    #         ("Flagged IXZZX Feed-Forward", "L0"),
    #         ("FT Logical X Measure", "L0")
    #     ]

    #     program_ftqec2 = QuantumProgram.from_quantum_program(
    #         self.program,
    #         stack_ftqec2,
    #         name="FT Prep -, QEC, FT measure X"
    #     )
    #     assert self._test_program(program_ftqec2, "Flagged IXZZX Check", 3)

    #     ## XIXZZ
    #     stack_ftqec3 = [
    #         ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}), # Autogenerated from state_type
    #         ("Init Patch 5Q", None, ("L0", self.qubits)), # Autogenerated from patch_types. Note that 5Q here must be a key into the patch_types dict below
    #         ("FT Minus Prep", "L0"),
    #         ("Flagged XIXZZ Check", "L0"),
    #         ("Flagged XIXZZ Feed-Forward", "L0"),
    #         ("FT Logical X Measure", "L0")
    #     ]

    #     program_ftqec3 = QuantumProgram.from_quantum_program(
    #         self.program,
    #         stack_ftqec3,
    #         name="FT Prep -, QEC, FT measure X"
    #     )
    #     assert self._test_program(program_ftqec3, "Flagged XIXZZ Check", 3)

    #     ## ZXIXZ
    #     stack_ftqec4 = [
    #         ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}), # Autogenerated from state_type
    #         ("Init Patch 5Q", None, ("L0", self.qubits)), # Autogenerated from patch_types. Note that 5Q here must be a key into the patch_types dict below
    #         ("FT Minus Prep", "L0"),
    #         ("Flagged ZXIXZ Check", "L0"),
    #         ("Flagged ZXIXZ Feed-Forward", "L0"),
    #         ("FT Logical X Measure", "L0")
    #     ]

    #     program_ftqec4 = QuantumProgram.from_quantum_program(
    #         self.program,
    #         stack_ftqec4,
    #         name="FT Prep -, QEC, FT measure X"
    #     )
    #     assert self._test_program(program_ftqec4, "Flagged ZXIXZ Check", 3)