"""Tester for loqs.codepacks.codepack_5_1_3_quantinuum"""

import pytest

from loqs.backends import GateRep, PyGSTiPhysicalCircuit, ListPhysicalCircuit, PyGSTiNoiseModel, DictNoiseModel, QSimQuantumState, STIMQuantumState
from loqs.core import Frame, Instruction, QuantumProgram
from loqs.codepacks import codepack_5_1_3_quantinuum2022 as codepack_5_1_3
from loqs.core.recordables import MeasurementOutcomes
from loqs.tools import fttools

class Test5QCodepack:

    @staticmethod
    def _create_program(circuit_backend, model_backend, state_backend):
        code_5q = codepack_5_1_3.create_qec_code(circuit_backend=circuit_backend)

        # Define the physical qubit labels for our system here
        qubits = ["A0", "A1"] + [f"D{i+2}" for i in range(5)]

        if state_backend == QSimQuantumState:
            gaterep = GateRep.QSIM_SUPEROPERATOR
        else:
            gaterep = GateRep.STIM_CIRCUIT_STR

        ideal_model = codepack_5_1_3.create_ideal_model(qubits, gaterep=gaterep, model_backend=model_backend)

        state_type = state_backend
        patch_types = {"5Q": code_5q}

        # Stack
        # The "Init *" instructions will be generated by the QuantumProgram based on the values
        # of state_type and patch_types below
        stack = [
            ("Init State", None, (len(qubits),), {"qubit_labels": qubits}), # Autogenerated from state_type
            ("Init Patch 5Q", None, ("L0", qubits)), # Autogenerated from patch_types. Note that 5Q here must be a key into the patch_types dict below
            ("Non-FT Minus Prep", "L0"),
            ("Non-FT Logical X Measure", "L0")
        ]

        return QuantumProgram(
            stack,
            default_noise_model=ideal_model,
            state_type=state_type,
            patch_types=patch_types,
            name="Prep minus, measure X"
        )

    @classmethod
    def setup_class(cls):
        cls.code_5Q = codepack_5_1_3.create_qec_code(circuit_backend=PyGSTiPhysicalCircuit)
        cls.program = cls._create_program(PyGSTiPhysicalCircuit, PyGSTiNoiseModel, QSimQuantumState)
        cls.stim_program = cls._create_program(PyGSTiPhysicalCircuit, DictNoiseModel, STIMQuantumState)
        cls.qubits = ["A0", "A1"] + [f"D{i+2}" for i in range(5)]
    
    # Note that tests will be labeled stack_outcome-state-model-circuit with this stacking
    @pytest.mark.parametrize("circuit_backend", [PyGSTiPhysicalCircuit, ListPhysicalCircuit])
    @pytest.mark.parametrize("model_backend", [PyGSTiNoiseModel, DictNoiseModel])
    @pytest.mark.parametrize("state_backend", [QSimQuantumState, STIMQuantumState])
    @pytest.mark.parametrize("stack_outcome", [
        ([("Non-FT Logical X Measure", "L0")], 1),
        ([("Z", "L0"), ("Non-FT Logical X Measure", "L0")], 0),
        ([("H", "L0"), ("Non-FT Logical Z Measure", "L0")], 1),
        ([("H", "L0"), ("X", "L0"), ("Non-FT Logical Z Measure", "L0")], 0),
    ])
    def test_nonft_workflow(self, circuit_backend, model_backend, state_backend, stack_outcome):
        if model_backend == PyGSTiNoiseModel and state_backend == STIMQuantumState:
            pytest.skip("PyGSTiNoiseModel cannot output STIM reps yet")
        
        ref_program = self._create_program(circuit_backend, model_backend, state_backend)

        stack = [
            ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}),
            ("Init Patch 5Q", None, ("L0",self.qubits)),
            ("Non-FT Minus Prep", "L0"),
        ]
        stack += stack_outcome[0]

        program = QuantumProgram.from_quantum_program(ref_program, stack)
        program_results = program.run()
        assert program_results.collect_shot_data("logical_measurement", -1)[0] == stack_outcome[1]

    # Note that tests will be labeled stack_outcome-state-model-circuit with this stacking
    @pytest.mark.parametrize("circuit_backend", [PyGSTiPhysicalCircuit, ListPhysicalCircuit])
    @pytest.mark.parametrize("model_backend", [PyGSTiNoiseModel, DictNoiseModel])
    @pytest.mark.parametrize("state_backend", [QSimQuantumState, STIMQuantumState])
    @pytest.mark.parametrize("stack_outcome", [
        ([("FT Logical X Measure", "L0")], 1),
        ([("Z", "L0"), ("Flagged QEC", "L0"), ("FT Logical X Measure", "L0")], 0),
    ])
    def test_ft_workflow(self, circuit_backend, model_backend, state_backend, stack_outcome):
        if model_backend == PyGSTiNoiseModel and state_backend == STIMQuantumState:
            pytest.skip("PyGSTiNoiseModel cannot output STIM reps yet")
        ref_program = self._create_program(circuit_backend, model_backend, state_backend)
        
        stack_ft = [
            ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}),
            ("Init Patch 5Q", None, ("L0",self.qubits)),
            ("FT Minus Prep", "L0")
        ]
        stack_ft += stack_outcome[0]

        program = QuantumProgram.from_quantum_program(ref_program, stack_ft)
        program_results = program.run()
        assert program_results.collect_shot_data("logical_measurement", -1)[0] == stack_outcome[1]
    

    def _test_program(self, program, key, idx):
        noise_injected_programs = fttools.build_discrete_error_injection_programs(
            base_program=program,
            instruction_to_analyze=self.code_5Q.instructions[key],
            stack_idx_to_modify=idx,
            error_circuit_labels=["Gxpi", "Gypi", "Gzpi"],
        )

        failed = fttools.run_discrete_error_injected_programs(
            noise_injected_programs,
            [("logical_measurement", -1)],
            [1],
        )
        return len(failed) == 0
    
    def test_all_discrete_errors_prep(self):
        stack_ftprep = [
            ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}),
            ("Init Patch 5Q", None, ("L0", self.qubits)),
            ("Non-FT Minus Prep", "L0"), # Make this one error, RUS should catch and rerun it
            ("FT Minus Prep", "L0"),
            ("FT Logical X Measure", "L0")
        ]

        program_ftprep = QuantumProgram.from_quantum_program(self.stim_program, stack_ftprep, name="FT Prep -, FT measure X")
        assert self._test_program(program_ftprep, "Non-FT Minus Prep", 2)

    def test_all_discrete_errors_meas(self):
        ## PART I
        stack_ftmeas_partI = [
            ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}), # Autogenerated from state_type
            ("Init Patch 5Q", None, ("L0", self.qubits)), # Autogenerated from patch_types. Note that 5Q here must be a key into the patch_types dict below
            ("FT Minus Prep", "L0"),
            ("FT Logical X Measure Part I Circuit", "L0"),
            ("FT Logical X Measure Part I Feed-Forward", "L0"),
        ]

        program_ftmeas_partI = QuantumProgram.from_quantum_program(self.stim_program, stack_ftmeas_partI, name="FT Prep -, non-FT measure X")
        assert self._test_program(program_ftmeas_partI, "FT Logical X Measure Part I Circuit", 3)

        ## PART II
        def ideal_partI_apply_fn():
            return Frame({"F1": 0, "inferred_M1": 1})

        ideal_partI = Instruction(
            ideal_partI_apply_fn,
            serialized_apply_fn="" # Hack, we won't need to serialize
        )

        stack_ftmeas_partII = [
            ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}), # Autogenerated from state_type
            ("Init Patch 5Q", None, ("L0", self.qubits)), # Autogenerated from patch_types. Note that 5Q here must be a key into the patch_types dict below
            ("FT Minus Prep", "L0"),
            ("FT Logical X Measure Part I Circuit", "L0"),
            ("Ideal Part I Feed-Forward", None), # Forward reference to global instruction
            ("FT Logical X Measure Part II Circuit", "L0"),
            ("FT Logical X Measure Part II Feed-Forward", "L0"),
        ]

        program_ftmeas_partII = QuantumProgram.from_quantum_program(
            self.stim_program,
            stack_ftmeas_partII,
            global_instructions={"Ideal Part I Feed-Forward": ideal_partI},
            name="FT Prep -, FT measure X"
        )
        assert self._test_program(program_ftmeas_partII, "FT Logical X Measure Part II Circuit", 5)

        ## PART III
        def ideal_partII_apply_fn():
            return Frame({"F2": 0, "inferred_M2": 1})

        ideal_partII = Instruction(
            ideal_partII_apply_fn,
            serialized_apply_fn="" # Hack, we won't need to serialize
        )

        stack_ftmeas_partIII = [
            ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}), # Autogenerated from state_type
            ("Init Patch 5Q", None, ("L0", self.qubits)), # Autogenerated from patch_types. Note that 5Q here must be a key into the patch_types dict below
            ("FT Minus Prep", "L0"),
            ("FT Logical X Measure Part I Circuit", "L0"),
            ("Ideal Part I Feed-Forward", None), # Forward reference to global instruction
            ("FT Logical X Measure Part II Circuit", "L0"),
            ("Ideal Part II Feed-Forward", None), # Forward reference to global instruction
            ("FT Logical X Measure Part III Circuit", "L0"),
            ("FT Logical X Measure Part III Feed-Forward", "L0"),
        ]

        program_ftmeas_partIII = QuantumProgram.from_quantum_program(
            self.stim_program,
            stack_ftmeas_partIII,
            global_instructions={
                "Ideal Part I Feed-Forward": ideal_partI,
                "Ideal Part II Feed-Forward": ideal_partII
            },
            name="FT Prep -, FT measure X"
        )
        assert self._test_program(program_ftmeas_partIII, "FT Logical X Measure Part III Circuit", 7)

    def test_all_discrete_errors_QEC(self):
        # XZZXI
        stack_ftqec1 = [
            ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}), # Autogenerated from state_type
            ("Init Patch 5Q", None, ("L0", self.qubits)), # Autogenerated from patch_types. Note that 5Q here must be a key into the patch_types dict below
            ("FT Minus Prep", "L0"),
            ("Flagged XZZXI Check", "L0"),
            ("Flagged XZZXI Feed-Forward", "L0"),
            ("FT Logical X Measure", "L0")
        ]

        program_ftqec1 = QuantumProgram.from_quantum_program(
            self.stim_program,
            stack_ftqec1,
            name="FT Prep -, QEC, FT measure X"
        )
        assert self._test_program(program_ftqec1, "Flagged XZZXI Check", 3)

        ## IXZZX
        stack_ftqec2 = [
            ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}), # Autogenerated from state_type
            ("Init Patch 5Q", None, ("L0", self.qubits)), # Autogenerated from patch_types. Note that 5Q here must be a key into the patch_types dict below
            ("FT Minus Prep", "L0"),
            ("Flagged IXZZX Check", "L0"),
            ("Flagged IXZZX Feed-Forward", "L0"),
            ("FT Logical X Measure", "L0")
        ]

        program_ftqec2 = QuantumProgram.from_quantum_program(
            self.stim_program,
            stack_ftqec2,
            name="FT Prep -, QEC, FT measure X"
        )
        assert self._test_program(program_ftqec2, "Flagged IXZZX Check", 3)

        ## XIXZZ
        stack_ftqec3 = [
            ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}), # Autogenerated from state_type
            ("Init Patch 5Q", None, ("L0", self.qubits)), # Autogenerated from patch_types. Note that 5Q here must be a key into the patch_types dict below
            ("FT Minus Prep", "L0"),
            ("Flagged XIXZZ Check", "L0"),
            ("Flagged XIXZZ Feed-Forward", "L0"),
            ("FT Logical X Measure", "L0")
        ]

        program_ftqec3 = QuantumProgram.from_quantum_program(
            self.stim_program,
            stack_ftqec3,
            name="FT Prep -, QEC, FT measure X"
        )
        assert self._test_program(program_ftqec3, "Flagged XIXZZ Check", 3)

        ## ZXIXZ
        stack_ftqec4 = [
            ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}), # Autogenerated from state_type
            ("Init Patch 5Q", None, ("L0", self.qubits)), # Autogenerated from patch_types. Note that 5Q here must be a key into the patch_types dict below
            ("FT Minus Prep", "L0"),
            ("Flagged ZXIXZ Check", "L0"),
            ("Flagged ZXIXZ Feed-Forward", "L0"),
            ("FT Logical X Measure", "L0")
        ]

        program_ftqec4 = QuantumProgram.from_quantum_program(
            self.stim_program,
            stack_ftqec4,
            name="FT Prep -, QEC, FT measure X"
        )
        assert self._test_program(program_ftqec4, "Flagged ZXIXZ Check", 3)
    
    def test_ft_prep_deep_spotcheck(self):
        stack_ftprep_D3X_error = [
            ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}),
            ("Init Patch 5Q", None, ("L0", self.qubits)),
            # Here we inject an X error before layer 2, i.e. between CZs, on qubit 4 (0-indexed, and our qubit convention is 2 aux + 5 data)
            ("Non-FT Minus Prep + Checks", "L0", (), {"error_injections": [(2, "Gxpi", 4)]}),
            # The RUS should do a check, then see that it failed, and do it all again
            ("FT Minus Prep", "L0", (), {"error_injections": [(2, "Gxpi", 4)]}),
            ("FT Logical X Measure", "L0")
        ]

        program_ftprep_D3X_error = QuantumProgram.from_quantum_program(self.program, stack_ftprep_D3X_error)
        assert fttools.test_program_output(
            program_ftprep_D3X_error,
            collect_shot_data_args=[
                ("measurement_outcomes", 2), # Let's grab the outcomes for the first round of RUS
                ("rus_success", 3),       # And also the computed RUS success value
                ("measurement_outcomes", 5), # Let's do it again for the second round (frame 3 is the reset)
                ("rus_success", 6),       
                ("logical_measurement", -1) # And still check the logical outcome
            ],
            expected_outcomes=[
                MeasurementOutcomes({"A0": [0, 0, 1], "A1": [0, 0, 0]}),
                False,
                MeasurementOutcomes({"A0": [0, 0, 0], "A1": [0, 0, 0]}),
                True,
                1
            ],
        )
    
    def test_ft_meas_deep_spotcheck(self):
        stack_ftmeas_partI_D2Z_error = [
            ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}),
            ("Init Patch 5Q", None, ("L0", self.qubits)),
            ("FT Minus Prep", "L0"),
            # Insert at layer 0, a Z error, on qubit 3 (0-indexed, where first 2 are aux qubits)
            ("FT Logical X Measure Part I Circuit", "L0", (), {"error_injections": [(0, "Gzpi", 3)]}),
            ("FT Logical X Measure Part I Feed-Forward", "L0"),
        ]

        program_ftmeas_partI_D2Z_error = QuantumProgram.from_quantum_program(self.program, stack_ftmeas_partI_D2Z_error)
        assert fttools.test_program_output(
            program_ftmeas_partI_D2Z_error,
            collect_shot_data_args=[
                ("log", 6),                # Double-check this is the Part I circuit result
                ("measurement_outcomes", 6),  # This should be all 0
                ("log", 7),                # Double-check this is the Part I feed-forward result
                ("F1", 7),                 # Should have no flag
                ("inferred_M1", 7),        # and this should have correctly identified logical 1 measurement
                ("log", 8),                # Double-check this is the Part II circuit result
                ("measurement_outcomes", 8),  # Now syndrome should be tripped
                ("log", 9),                # Double-check this is the Part II feed-forward result
                ("F2", 9),                 # Should have no flag
                ("inferred_M2", 9),        # but incorrectly identify logical 0 measurement
                ("log", 10),                # We should now hit decoder circuit
                ("measurement_outcomes", 10), # The Z error should show up as a bitflip on data qubit 2
                ("log", 11),                # Finally we hit the classical decoder
                ("classical_correction", 11), # Let's see that the decoder picked out the correct error...
                ("corrected_outcomes", 11), # ... and applied the correction properly
                ("logical_measurement", 11) # And still check the logical outcome
            ],
            expected_outcomes=[
                "FT Logical X Measure Part I Circuit result",
                MeasurementOutcomes({"A0": [0], "A1": [0]}),
                "FT Logical X Measure Part I Feed-Forward result",
                0,
                1,
                "FT Logical X Measure Part II Circuit result",
                MeasurementOutcomes({"A0": [1], "A1": [0]}),
                "FT Logical X Measure Part II Feed-Forward result",
                0,
                0,
                "Non-FT state decoder circuit result",
                MeasurementOutcomes({"D2": [0], "D3": [1], "D4": [0], "D5": [0], "D6": [0]}),
                "FT Logical X Measure Classical Decoder result",
                "IXIII", # Remember that this is the decoded error
                [0, 0, 0, 0, 0],
                1
            ],
            verbose=True
        )
    
        stack_ftmeas_partI_M1X_error = [
            ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}),
            ("Init Patch 5Q", None, ("L0", self.qubits)),
            ("FT Minus Prep", "L0"),
            # Insert at layer 3, a X error, on qubit 0 (0-indexed, where first qubit is measure qubit)
            ("FT Logical X Measure Part I Circuit", "L0", (), {"error_injections": [(3, "Gxpi", 0)]}),
            ("FT Logical X Measure Part I Feed-Forward", "L0"),
        ]

        program_ftmeas_partI_M1X_error = QuantumProgram.from_quantum_program(self.program, stack_ftmeas_partI_M1X_error)
        assert fttools.test_program_output(
            program_ftmeas_partI_M1X_error,
            collect_shot_data_args=[
                ("log", 6),                # Double-check this is the Part I circuit result
                ("measurement_outcomes", 6),  # An X error is undetectable on measure, but it should trip the flag!
                ("log", 7),                # Double-check this is the Part I feed-forward result
                ("F1", 7),                 # We should have a flag...
                ("inferred_M1", 7),        # ... but still think this is logical 1
                ("log", 8),                # We should now hit decoder circuit
                # The expected measurement outcome is non-trivial.
                # The X error on data qubit 1 will prop to Z errors on data qubit 2 and 5
                # This will cancel the Z error on data qubit 2, but show up as a bitflip on data qubit 5
                ("measurement_outcomes", 8),
                ("log", 9),                # Finally we hit the classical decoder
                ("classical_correction", 9), # Let's see that the decoder picked out the correct error...
                ("corrected_outcomes", 9), # ... and applied the correction properly
                ("logical_measurement", 9) # And still check the logical outcome
            ],
            expected_outcomes=[
                "FT Logical X Measure Part I Circuit result",
                MeasurementOutcomes({"A0": [0], "A1": [1]}),
                "FT Logical X Measure Part I Feed-Forward result",
                1,
                1,
                "Non-FT state decoder circuit result",
                MeasurementOutcomes({"D2": [0], "D3": [0], "D4": [0], "D5": [0], "D6": [1]}),
                "FT Logical X Measure Classical Decoder result",
                "IIIIX", # Remember that this is the decoded error
                [0, 0, 0, 0, 0],
                1
            ]
        )
            