"""Tester for loqs.codepacks.codepack_7_1_3_quantinuum2021"""

import pytest

# TODO: Rework to run with native backend only if failure to import
quantumsim = pytest.importorskip("quantumsim")
pygsti = pytest.importorskip("pygsti")
stim = pytest.importorskip("stim")


from loqs.backends import GateRep, PyGSTiPhysicalCircuit, ListPhysicalCircuit, PyGSTiNoiseModel, DictNoiseModel, QSimQuantumState, STIMQuantumState
from loqs.core import Frame, Instruction, QuantumProgram
from loqs.codepacks import codepack_7_1_3_quantinuum2021 as codepack_steane
from loqs.core.instructions import builders
from loqs.core.recordables import MeasurementOutcomes
from loqs.tools import fttools

class TestSteaneCodepack:

    @staticmethod
    def _create_program(circuit_backend, model_backend, state_backend):
        code_steane = codepack_steane.create_qec_code(circuit_backend=circuit_backend)

        # Define the physical qubit labels for our system here
        qubits = ["A0", "A1", "A2"] + [f"D{i+3}" for i in range(7)]

        if state_backend == QSimQuantumState:
            gaterep = GateRep.QSIM_SUPEROPERATOR
        else:
            gaterep = GateRep.STIM_CIRCUIT_STR

        ideal_model = codepack_steane.create_ideal_model(qubits, gaterep=gaterep, model_backend=model_backend)

        state_type = state_backend
        patch_types = {"Steane": code_steane}

        # Stack
        # The "Init *" instructions will be generated by the QuantumProgram based on the values
        # of state_type and patch_types below
        stack = [
            ("Init State", None, (len(qubits),), {"qubit_labels": qubits}), # Autogenerated from state_type
            ("Init Patch Steane", None, ("L0", qubits)), # Autogenerated from patch_types. Note that 5Q here must be a key into the patch_types dict below
            ("Non-FT Zero Prep", "L0"),
            ("FT Logical Z Measure", "L0")
        ]

        return QuantumProgram(
            stack,
            default_noise_model=ideal_model,
            state_type=state_type,
            patch_types=patch_types,
            name="Prep zero, measure Z"
        )

    @classmethod
    def setup_class(cls):
        cls.code_steane = codepack_steane.create_qec_code(circuit_backend=PyGSTiPhysicalCircuit)
        cls.program = cls._create_program(PyGSTiPhysicalCircuit, PyGSTiNoiseModel, QSimQuantumState)
        cls.qubits = ["A0", "A1", "A2"] + [f"D{i+3}" for i in range(7)]
    
    # Note that tests will be labeled stack_outcome-state-model-circuit with this stacking
    @pytest.mark.parametrize("circuit_backend", [PyGSTiPhysicalCircuit, ListPhysicalCircuit])
    @pytest.mark.parametrize("model_backend", [PyGSTiNoiseModel, DictNoiseModel])
    @pytest.mark.parametrize("state_backend", [QSimQuantumState, STIMQuantumState])
    @pytest.mark.parametrize("stack_outcome", [
        ([("FT Logical Z Measure", "L0")], 0),
        ([("X", "L0"), ("FT Logical Z Measure", "L0")], 1),
        ([("H", "L0"), ("FT Logical X Measure", "L0")], 0),
        ([("H", "L0"), ("Z", "L0"), ("FT Logical X Measure", "L0")], 1),
    ])
    def test_nonft_workflow(self, circuit_backend, model_backend, state_backend, stack_outcome):
        if model_backend == PyGSTiNoiseModel and state_backend == STIMQuantumState:
            pytest.skip("PyGSTiNoiseModel cannot output STIM reps yet")
        
        ref_program = self._create_program(circuit_backend, model_backend, state_backend)

        stack = [
            ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}),
            ("Init Patch Steane", None, ("L0",self.qubits)),
            ("Non-FT Zero Prep", "L0"),
        ]
        stack += stack_outcome[0]

        program = QuantumProgram.from_quantum_program(ref_program, stack)
        program_results = program.run()
        assert program_results.collect_shot_data("logical_measurement", -1)[0] == stack_outcome[1]

    # Note that tests will be labeled stack_outcome-state-model-circuit with this stacking
    @pytest.mark.parametrize("circuit_backend", [PyGSTiPhysicalCircuit, ListPhysicalCircuit])
    @pytest.mark.parametrize("model_backend", [PyGSTiNoiseModel, DictNoiseModel])
    @pytest.mark.parametrize("state_backend", [QSimQuantumState, STIMQuantumState])
    @pytest.mark.parametrize("stack_outcome", [
        ([("FT Logical Z Measure", "L0")], 0),
        ([("X", "L0"), ("Adaptive QEC", "L0"), ("FT Logical Z Measure", "L0")], 1),
    ])
    def test_ft_workflow(self, circuit_backend, model_backend, state_backend, stack_outcome):
        if model_backend == PyGSTiNoiseModel and state_backend == STIMQuantumState:
            pytest.skip("PyGSTiNoiseModel cannot output STIM reps yet")
        ref_program = self._create_program(circuit_backend, model_backend, state_backend)
        
        stack_ft = [
            ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}),
            ("Init Patch Steane", None, ("L0",self.qubits)),
            ("FT Zero Prep", "L0")
        ]
        stack_ft += stack_outcome[0]

        program = QuantumProgram.from_quantum_program(ref_program, stack_ft)
        program_results = program.run()
        assert program_results.collect_shot_data("logical_measurement", -1)[0] == stack_outcome[1]

    # Regression test for over-correction of the logical Pauli frame in
    # ``logical_meas_apply_fn``.
    #
    # A data error that commutes with the measurement basis (e.g. a Z error
    # before a logical Z measurement) does not change the logical outcome.
    # However, the QEC rounds detect that error and record a correction in the
    # logical Pauli frame. The previous implementation of the final logical
    # measurement (a) read the wrong frame component and (b) decoded the
    # absolute reconstructed syndrome instead of the difference against the
    # last recorded syndrome, so the frame correction was applied on top of an
    # already-correct raw outcome -- flipping it. This double counting is the
    # over-correction. Here we inject a single commuting Pauli error, run one
    # or more QEC rounds, and assert the logical outcome is still 0.
    #
    # Scoped to STIMQuantumState + DictNoiseModel only (per request).
    @pytest.mark.parametrize("num_qec_rounds", [1, 2])
    @pytest.mark.parametrize("data_qubit", [f"D{i+3}" for i in range(7)])
    @pytest.mark.parametrize("error_gate", ["Gzpi", "Gypi"])
    def test_logical_meas_no_pauli_frame_overcorrection(
        self, error_gate, data_qubit, num_qec_rounds
    ):
        # A physical single-qubit error on one data qubit. ``Gzpi``/``Gypi``
        # both contain a Z component, which commutes with the logical Z-basis
        # measurement and so must not change the logical outcome.
        self._assert_single_error_corrected(
            measurement_basis="Z",
            error_gate=error_gate,
            data_qubit=data_qubit,
            num_qec_rounds=num_qec_rounds,
        )

    # Single-fault correctness: any single-qubit Pauli error on any data qubit
    # must be corrected by the final logical measurement, with or without QEC
    # rounds. This locks in the fix to which qubits contribute to the raw
    # logical outcome (the weight-3 logical representative, consistent with the
    # ``data_decode`` flip table). In particular it covers the D3 edge case
    # that previously failed even with zero QEC rounds.
    #
    # Scoped to STIMQuantumState + DictNoiseModel only (per request).
    @pytest.mark.parametrize("num_qec_rounds", [0, 1])
    @pytest.mark.parametrize("data_qubit", [f"D{i+3}" for i in range(7)])
    @pytest.mark.parametrize("error_gate", ["Gxpi", "Gypi", "Gzpi"])
    @pytest.mark.parametrize("measurement_basis", ["Z", "X"])
    def test_single_data_error_corrected(
        self, measurement_basis, error_gate, data_qubit, num_qec_rounds
    ):
        self._assert_single_error_corrected(
            measurement_basis=measurement_basis,
            error_gate=error_gate,
            data_qubit=data_qubit,
            num_qec_rounds=num_qec_rounds,
        )

    def _assert_single_error_corrected(
        self, measurement_basis, error_gate, data_qubit, num_qec_rounds
    ):
        circuit_backend = ListPhysicalCircuit
        code = codepack_steane.create_qec_code(circuit_backend=circuit_backend)
        model = codepack_steane.create_ideal_model(
            self.qubits,
            gaterep=GateRep.STIM_CIRCUIT_STR,
            model_backend=DictNoiseModel,
        )

        error_circ = circuit_backend(
            [[(error_gate, data_qubit)]], qubit_labels=self.qubits
        )
        code.instructions["Injected Data Error"] = (
            builders.build_physical_circuit_instruction(
                error_circ, name="Injected Data Error"
            )
        )

        stack = [
            ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}),
            ("Init Patch Steane", None, ("L0", self.qubits)),
            ("FT Zero Prep", "L0"),
        ]
        # Logical |0> measures to 0 in Z; logical |+> measures to 0 in X.
        if measurement_basis == "X":
            stack.append(("H", "L0"))
        stack.append(("Injected Data Error", "L0"))
        stack += [("Adaptive QEC", "L0")] * num_qec_rounds
        stack.append((f"FT Logical {measurement_basis} Measure", "L0"))

        program = QuantumProgram(
            stack,
            default_noise_model=model,
            state_type=STIMQuantumState,
            patch_types={"Steane": code},
            name="single-fault correctness",
        )
        program_results = program.run()
        assert (
            program_results.collect_shot_data("logical_measurement", -1)[0] == 0
        )

    def _test_program(self, program, key, idx):
        noise_injected_programs = fttools.build_discrete_error_injection_programs(
            base_program=program,
            instruction_to_analyze=self.code_steane.instructions[key],
            stack_idx_to_modify=idx,
            error_circuit_labels=["Gxpi", "Gypi", "Gzpi"],
        )

        failed = fttools.run_discrete_error_injected_programs(
            noise_injected_programs,
            [("logical_measurement", -1)],
            [0],
        )
        return len(failed)
    
    def test_qec_ft_branch1(self):
        stack_ftqec1 = [
            ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}),
            ("Init Patch Steane", None, ("L0", self.qubits)),
            ("FT Zero Prep", "L0"),
            ("Flagged Parallel S1-S5-S6 Check", "L0"),  # index 3
            ("Flagged S1-S5-S6 Feed-Forward", "L0"),
            ("FT Logical Z Measure", "L0"),
        ]

        ref_program = self._create_program(ListPhysicalCircuit, DictNoiseModel, STIMQuantumState)
        program_ftqec1 = QuantumProgram.from_quantum_program(
            ref_program,
            stack_ftqec1,
            name="QEC FT Branch 1 Test",
        )
        assert self._test_program(program_ftqec1, "Flagged Parallel S1-S5-S6 Check", 3) <= 2

    def test_qec_ft_branch2(self):
        stack_ftqec2 = [
            ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}),
            ("Init Patch Steane", None, ("L0", self.qubits)),
            ("FT Zero Prep", "L0"),
            ("Flagged Parallel S2-S3-S4 Check", "L0"),  # index 3
            ("Flagged S2-S3-S4 Feed-Forward", "L0"),
            ("FT Logical Z Measure", "L0"),
        ]

        ref_program = self._create_program(ListPhysicalCircuit, DictNoiseModel, STIMQuantumState)
        program_ftqec2 = QuantumProgram.from_quantum_program(
            ref_program,
            stack_ftqec2,
            name="QEC FT Branch 2 Test",
        )
        assert self._test_program(program_ftqec2, "Flagged Parallel S2-S3-S4 Check", 3) <= 2

    def test_measurement_ft_Z(self):
        stack_meas_Z = [
            ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}),
            ("Init Patch Steane", None, ("L0", self.qubits)),
            ("FT Zero Prep", "L0"),
            ("Raw Z Data Measure", "L0"),  # index 3
            ("FT Z logical parity calculation", "L0"),
        ]

        ref_program = self._create_program(ListPhysicalCircuit, DictNoiseModel, STIMQuantumState)
        program_meas_Z = QuantumProgram.from_quantum_program(
            ref_program,
            stack_meas_Z,
            name="Measurement FT Z Test",
        )
        assert self._test_program(program_meas_Z, "Raw Z Data Measure", 3) == 0

    def test_measurement_ft_X(self):
        stack_meas_X = [
            ("Init State", None, (len(self.qubits),), {"qubit_labels": self.qubits}),
            ("Init Patch Steane", None, ("L0", self.qubits)),
            ("FT Zero Prep", "L0"),
            ("H", "L0"),  # Prep +
            ("Raw X Data Measure", "L0"),  # index 4
            ("FT X logical parity calculation", "L0"),
        ]

        ref_program = self._create_program(ListPhysicalCircuit, DictNoiseModel, STIMQuantumState)
        program_meas_X = QuantumProgram.from_quantum_program(
            ref_program,
            stack_meas_X,
            name="Measurement FT X Test",
        )
        assert self._test_program(program_meas_X, "Raw X Data Measure", 4) == 0