# Main reusable LoQS test runner

name: Core LoQS tests

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      loqs-optional:
        required: true
        type: string

jobs:
  build-and-test:
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    
    # On Windows, set up MSVC
    # Originally needed because no pymatching 3.14 wheels
    - name: Set up MSVC
      if: ${{ inputs.os == 'windows-latest' }}
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    
    - name: Verify MSVC is on PATH
      if: ${{ inputs.os == 'windows-latest' }}
      shell: pwsh
      run: |
        where.exe cl
        cl /Bv
        where.exe cmake
        cmake --version

        python -m pip install --upgrade pip
        python -m pip install cmake ninja
  
    - name: Cache pip environments
      uses: actions/cache@v4
      id: pip-cache-id
      with:
        path: ~/.cache/pip
        key: ${{ inputs.os }}-${{ inputs.python-version }}-pip-${{ inputs.loqs-optional }}
        restore-keys: |
          ${{ inputs.os }}-${{ inputs.python-version }}-pip-
    
    # TODO: This can be simplified and made more consistent by using existing tox config with tox-gh
    
    - name: Install non-Windows loqs[${{ inputs.loqs-optional }}]
      if: ${{ inputs.os != 'windows-latest' }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install ".[${{ inputs.loqs-optional }}]"
    
    # Set up CMake environment in case we need to build wheels
    - name: Install Windows loqs[${{ inputs.loqs-optional }}]
      if: ${{ inputs.os == 'windows-latest' }}
      shell: pwsh
      env:
        CMAKE_GENERATOR: Ninja
        CMAKE_BUILD_PARALLEL_LEVEL: 1
        CMAKE_ARGS: >-
          -DCMAKE_MSVC_DEBUG_INFORMATION_FORMAT=Embedded
        CC: cl
        CXX: cl
      run: |
        python -m pip install pymatching
        python -m pip install ".[${{ inputs.loqs-optional }}]"
  
    - name: Linting
      run: |
        # Format check, allow failure
        python -m black --check loqs || true
        
        # Standard PEP8, allowed to fail since exit-zero treats all errors as warnings
        python -m flake8 loqs --exit-zero --statistics
    
    - name: Type checking
      run: |
        # Allow to fail
        python -m mypy loqs || true
    
    - name: Docstring tests
      run: |
        python -m pytest loqs
    
    - name: Unit tests (with coverage)
      run: |
        python -m pytest --cov=loqs --cov-branch --cov-report term-missing --cov-report xml:coverage.xml tests
    
    - name: Upload coverage to Coveralls (only one matrix element)
      uses: coverallsapp/github-action@v2
      if: ${{ inputs.os == 'ubuntu-latest' && inputs.python-version == '3.11' && inputs.loqs-optional == 'all' }}
      with:
        format: cobertura
        file: coverage.xml








